-- Generated by scripts/oracle-db/content-array-reference.mjs from CONTENT_ARRAY_REFERENCES.
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '30s';
LOCK TABLE public.contents, public.faction_lv2, public.flow_nodes, public.flows, public.tier_lists IN SHARE ROW EXCLUSIVE MODE;

CREATE FUNCTION public.content_array_reference_ids(value jsonb, shape text)
RETURNS SETOF text LANGUAGE plpgsql IMMUTABLE SET search_path = pg_catalog, public AS $function$
DECLARE entry jsonb; tier jsonb;
BEGIN
  IF value IS NULL OR value = 'null'::jsonb THEN RETURN; END IF;
  IF shape = 'tiers' THEN
    IF jsonb_typeof(value) <> 'object' THEN
      RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'content tiers must be an object of ID arrays';
    END IF;
    FOR tier IN SELECT v FROM jsonb_each(value) AS t(k, v) LOOP
      RETURN QUERY SELECT * FROM public.content_array_reference_ids(tier, 'array');
    END LOOP;
    RETURN;
  END IF;
  IF shape <> 'array' OR jsonb_typeof(value) <> 'array' THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'content IDs must be an array';
  END IF;
  FOR entry IN SELECT v FROM jsonb_array_elements(value) AS t(v) LOOP
    IF jsonb_typeof(entry) <> 'string' THEN
      RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'content ID array members must be strings';
    END IF;
    RETURN NEXT entry #>> '{}';
  END LOOP;
END;
$function$;

CREATE FUNCTION public.check_content_array_references()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, public SET row_security = off AS $function$
DECLARE row_json jsonb := to_jsonb(NEW); refs jsonb; ref record;
BEGIN
  IF TG_TABLE_NAME = 'faction_lv2' THEN
    SELECT coalesce(jsonb_agg(to_jsonb(referenced) ORDER BY content_id, column_name), '[]'::jsonb) INTO refs
    FROM (SELECT content_id, 'theme_book_ids'::text AS column_name FROM public.content_array_reference_ids(row_json->'theme_book_ids', 'array') content_id) referenced;
  ELSIF TG_TABLE_NAME = 'flow_nodes' THEN
    SELECT coalesce(jsonb_agg(to_jsonb(referenced) ORDER BY content_id, column_name), '[]'::jsonb) INTO refs
    FROM (SELECT content_id, 'bonus_content_ids'::text AS column_name FROM public.content_array_reference_ids(row_json->'bonus_content_ids', 'array') content_id) referenced;
  ELSIF TG_TABLE_NAME = 'flows' THEN
    SELECT coalesce(jsonb_agg(to_jsonb(referenced) ORDER BY content_id, column_name), '[]'::jsonb) INTO refs
    FROM (SELECT content_id, 'tiers'::text AS column_name FROM public.content_array_reference_ids(row_json->'tiers', 'tiers') content_id) referenced;
  ELSIF TG_TABLE_NAME = 'tier_lists' THEN
    SELECT coalesce(jsonb_agg(to_jsonb(referenced) ORDER BY content_id, column_name), '[]'::jsonb) INTO refs
    FROM (SELECT content_id, 'tiers'::text AS column_name FROM public.content_array_reference_ids(row_json->'tiers', 'tiers') content_id
      UNION
      SELECT content_id, 'unranked'::text AS column_name FROM public.content_array_reference_ids(row_json->'unranked', 'array') content_id) referenced;
  ELSE RAISE EXCEPTION 'unsupported content reference table: %', TG_TABLE_NAME;
  END IF;
  FOR ref IN SELECT * FROM jsonb_to_recordset(refs) AS r(content_id text, column_name text) LOOP
    PERFORM 1 FROM public.contents c WHERE c.id = ref.content_id FOR KEY SHARE;
    IF NOT FOUND THEN
      RAISE EXCEPTION USING ERRCODE = '23503', MESSAGE = 'array references a missing content',
        DETAIL = format('content_id=%s', ref.content_id), TABLE = TG_TABLE_NAME, COLUMN = ref.column_name,
        CONSTRAINT = TG_TABLE_NAME || '_content_array_reference_guard';
    END IF;
  END LOOP;
  RETURN NEW;
END;
$function$;

CREATE FUNCTION public.lock_content_array_references_for_identity_change()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, public SET row_security = off AS $function$
BEGIN
  LOCK TABLE public.faction_lv2, public.flow_nodes, public.flows, public.tier_lists IN SHARE ROW EXCLUSIVE MODE;
  RETURN NULL;
END;
$function$;

CREATE FUNCTION public.reject_referenced_content_identity_change()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, public SET row_security = off AS $function$
BEGIN
  IF TG_OP = 'UPDATE' THEN
    IF OLD.id IS NOT DISTINCT FROM NEW.id THEN RETURN NEW; END IF;
  END IF;
  -- A fixed transaction snapshot can miss a reference committed after it began.
  -- Retry an identity change in READ COMMITTED; unchanged IDs remain allowed.
  IF current_setting('transaction_isolation') NOT IN ('read committed', 'read uncommitted') THEN
    RAISE EXCEPTION USING ERRCODE = '40001', MESSAGE = 'content identity change requires READ COMMITTED',
      HINT = 'Retry the identity change transaction with READ COMMITTED isolation.';
  END IF;

  IF EXISTS (SELECT 1 FROM public.flow_nodes t
    CROSS JOIN LATERAL public.content_array_reference_ids(t.bonus_content_ids, 'array') ref(content_id)
    WHERE ref.content_id = OLD.id) THEN
    RAISE EXCEPTION USING ERRCODE = '23503', MESSAGE = 'content is referenced by flow_nodes.bonus_content_ids',
      DETAIL = format('content_id=%s', OLD.id), TABLE = 'flow_nodes', COLUMN = 'bonus_content_ids',
      CONSTRAINT = 'contents_array_reference_guard';
  END IF;

  IF EXISTS (SELECT 1 FROM public.flows t
    CROSS JOIN LATERAL public.content_array_reference_ids(t.tiers, 'tiers') ref(content_id)
    WHERE ref.content_id = OLD.id) THEN
    RAISE EXCEPTION USING ERRCODE = '23503', MESSAGE = 'content is referenced by flows.tiers',
      DETAIL = format('content_id=%s', OLD.id), TABLE = 'flows', COLUMN = 'tiers',
      CONSTRAINT = 'contents_array_reference_guard';
  END IF;

  IF EXISTS (SELECT 1 FROM public.tier_lists t
    CROSS JOIN LATERAL public.content_array_reference_ids(t.tiers, 'tiers') ref(content_id)
    WHERE ref.content_id = OLD.id) THEN
    RAISE EXCEPTION USING ERRCODE = '23503', MESSAGE = 'content is referenced by tier_lists.tiers',
      DETAIL = format('content_id=%s', OLD.id), TABLE = 'tier_lists', COLUMN = 'tiers',
      CONSTRAINT = 'contents_array_reference_guard';
  END IF;

  IF EXISTS (SELECT 1 FROM public.tier_lists t
    CROSS JOIN LATERAL public.content_array_reference_ids(to_jsonb(t.unranked), 'array') ref(content_id)
    WHERE ref.content_id = OLD.id) THEN
    RAISE EXCEPTION USING ERRCODE = '23503', MESSAGE = 'content is referenced by tier_lists.unranked',
      DETAIL = format('content_id=%s', OLD.id), TABLE = 'tier_lists', COLUMN = 'unranked',
      CONSTRAINT = 'contents_array_reference_guard';
  END IF;

  IF EXISTS (SELECT 1 FROM public.faction_lv2 t
    CROSS JOIN LATERAL public.content_array_reference_ids(to_jsonb(t.theme_book_ids), 'array') ref(content_id)
    WHERE ref.content_id = OLD.id) THEN
    RAISE EXCEPTION USING ERRCODE = '23503', MESSAGE = 'content is referenced by faction_lv2.theme_book_ids',
      DETAIL = format('content_id=%s', OLD.id), TABLE = 'faction_lv2', COLUMN = 'theme_book_ids',
      CONSTRAINT = 'contents_array_reference_guard';
  END IF;
  IF TG_OP = 'UPDATE' THEN RETURN NEW; END IF;
  RETURN OLD;
END;
$function$;

DO $validation$
BEGIN

  IF EXISTS (SELECT 1 FROM public.flow_nodes t
    CROSS JOIN LATERAL public.content_array_reference_ids(t.bonus_content_ids, 'array') ref(content_id)
    LEFT JOIN public.contents c ON c.id = ref.content_id WHERE c.id IS NULL) THEN
    RAISE EXCEPTION USING ERRCODE = '23503', MESSAGE = 'existing missing content in flow_nodes.bonus_content_ids';
  END IF;

  IF EXISTS (SELECT 1 FROM public.flows t
    CROSS JOIN LATERAL public.content_array_reference_ids(t.tiers, 'tiers') ref(content_id)
    LEFT JOIN public.contents c ON c.id = ref.content_id WHERE c.id IS NULL) THEN
    RAISE EXCEPTION USING ERRCODE = '23503', MESSAGE = 'existing missing content in flows.tiers';
  END IF;

  IF EXISTS (SELECT 1 FROM public.tier_lists t
    CROSS JOIN LATERAL public.content_array_reference_ids(t.tiers, 'tiers') ref(content_id)
    LEFT JOIN public.contents c ON c.id = ref.content_id WHERE c.id IS NULL) THEN
    RAISE EXCEPTION USING ERRCODE = '23503', MESSAGE = 'existing missing content in tier_lists.tiers';
  END IF;

  IF EXISTS (SELECT 1 FROM public.tier_lists t
    CROSS JOIN LATERAL public.content_array_reference_ids(to_jsonb(t.unranked), 'array') ref(content_id)
    LEFT JOIN public.contents c ON c.id = ref.content_id WHERE c.id IS NULL) THEN
    RAISE EXCEPTION USING ERRCODE = '23503', MESSAGE = 'existing missing content in tier_lists.unranked';
  END IF;

  IF EXISTS (SELECT 1 FROM public.faction_lv2 t
    CROSS JOIN LATERAL public.content_array_reference_ids(to_jsonb(t.theme_book_ids), 'array') ref(content_id)
    LEFT JOIN public.contents c ON c.id = ref.content_id WHERE c.id IS NULL) THEN
    RAISE EXCEPTION USING ERRCODE = '23503', MESSAGE = 'existing missing content in faction_lv2.theme_book_ids';
  END IF;
END;
$validation$;

CREATE TRIGGER faction_lv2_content_array_reference_guard
  BEFORE INSERT OR UPDATE OF theme_book_ids ON public.faction_lv2
  FOR EACH ROW EXECUTE FUNCTION public.check_content_array_references();
CREATE TRIGGER flow_nodes_content_array_reference_guard
  BEFORE INSERT OR UPDATE OF bonus_content_ids ON public.flow_nodes
  FOR EACH ROW EXECUTE FUNCTION public.check_content_array_references();
CREATE TRIGGER flows_content_array_reference_guard
  BEFORE INSERT OR UPDATE OF tiers ON public.flows
  FOR EACH ROW EXECUTE FUNCTION public.check_content_array_references();
CREATE TRIGGER tier_lists_content_array_reference_guard
  BEFORE INSERT OR UPDATE OF tiers, unranked ON public.tier_lists
  FOR EACH ROW EXECUTE FUNCTION public.check_content_array_references();
CREATE TRIGGER contents_array_reference_identity_lock
  BEFORE DELETE OR UPDATE OF id ON public.contents FOR EACH STATEMENT
  EXECUTE FUNCTION public.lock_content_array_references_for_identity_change();
CREATE TRIGGER contents_array_reference_identity_guard
  BEFORE DELETE OR UPDATE OF id ON public.contents FOR EACH ROW
  EXECUTE FUNCTION public.reject_referenced_content_identity_change();
COMMIT;
