// Keep loading geometry tied to the atlas at every breakpoint.
export const MYTH_LAYOUT = {
  atlas: "scroll-mt-20 overflow-hidden rounded-[28px] border border-white/[0.08] bg-[radial-gradient(circle_at_50%_0%,rgba(217,181,78,.045),transparent_30%),var(--color-bg-secondary)] [overflow-anchor:none]",
  container: "mx-auto max-w-[1040px]",
  navigationOuter: "px-4 pb-2 pt-4 md:px-6 md:pb-2 md:pt-6",
  navigation: "mx-auto grid max-w-[1040px] gap-1 overflow-hidden rounded-[20px] border border-white/[0.08] bg-black/[0.16] p-2",
  nav: "min-w-0 rounded-xl px-2 py-3 md:px-3",
  navList: "scrollbar-hide -mx-1 mt-2.5 flex justify-start gap-1.5 overflow-x-auto px-1 pb-1 md:flex-wrap md:justify-center md:overflow-visible",
  notice: "mx-2 mb-1 flex items-start justify-center gap-2 rounded-xl border border-accent/[0.12] bg-accent/[0.035] px-3 py-2.5 text-center text-xs leading-5 text-text-tertiary md:mx-3",
  railOuter: "px-4 py-2 md:px-6",
  rail: "min-w-0 overflow-hidden rounded-[20px] border border-white/[0.08] bg-black/[0.12] px-4 py-4 md:px-5 md:py-5",
  railCardSize: "w-[96px] md:w-[108px]",
  overviewOuter: "min-w-0 px-4 pb-4 pt-2 md:px-6 md:pb-6",
  overview: "overflow-hidden rounded-[24px] border border-white/[0.08] bg-black",
  artwork: "relative aspect-[3/2] w-full overflow-hidden",
  overviewPanel: "relative z-10 bg-black px-5 pb-6 pt-5 md:px-7 md:pb-7 md:pt-6 lg:absolute lg:inset-y-0 lg:end-0 lg:flex lg:w-[43%] lg:items-center lg:bg-transparent lg:px-6 lg:py-8 xl:px-8",
  overviewBody: "flex w-full min-w-0 flex-col lg:h-[430px] lg:rounded-[20px] lg:border lg:border-white/[0.09] lg:bg-black/[0.88] lg:p-6 lg:shadow-[0_18px_44px_rgba(0,0,0,.28)]",
  overviewHeader: "flex flex-wrap items-center justify-between gap-x-3 gap-y-2",
  overviewStats: "min-w-0 text-end text-[11px] font-semibold leading-5 text-text-tertiary md:text-xs",
  description: "scrollbar-thin mt-4 h-56 overflow-y-auto pe-2 [overflow-anchor:none] md:h-64 lg:min-h-0 lg:flex-1",
  entryLabel: "text-[11px] font-bold tracking-[.14em]",
  entryTitle: "mt-0.5 min-h-10 line-clamp-2 text-sm font-bold leading-5",
  entryCreator: "mt-0.5 h-4 truncate text-xs text-text-secondary",
} as const;
