/*
  지도 원본(Natural Earth 110m)이 가진 영문 나라 이름 → 한국어
  - 키는 `public/data/world-110m.json`의 properties.name 과 글자 하나까지 같아야 한다
  - 목록에 없는 이름은 원문을 그대로 보여준다
*/

export const COUNTRY_NAMES_KO: Record<string, string> = {
  Afghanistan: "아프가니스탄",
  Albania: "알바니아",
  Algeria: "알제리",
  Angola: "앙골라",
  Antarctica: "남극",
  Argentina: "아르헨티나",
  Armenia: "아르메니아",
  Australia: "오스트레일리아",
  Austria: "오스트리아",
  Azerbaijan: "아제르바이잔",
  Bahamas: "바하마",
  Bangladesh: "방글라데시",
  Belarus: "벨라루스",
  Belgium: "벨기에",
  Belize: "벨리즈",
  Benin: "베냉",
  Bhutan: "부탄",
  Bolivia: "볼리비아",
  "Bosnia and Herz.": "보스니아 헤르체고비나",
  Botswana: "보츠와나",
  Brazil: "브라질",
  Brunei: "브루나이",
  Bulgaria: "불가리아",
  "Burkina Faso": "부르키나파소",
  Burundi: "부룬디",
  Cambodia: "캄보디아",
  Cameroon: "카메룬",
  Canada: "캐나다",
  "Central African Rep.": "중앙아프리카공화국",
  Chad: "차드",
  Chile: "칠레",
  China: "중국",
  Colombia: "콜롬비아",
  Congo: "콩고",
  "Costa Rica": "코스타리카",
  Croatia: "크로아티아",
  Cuba: "쿠바",
  Cyprus: "키프로스",
  Czechia: "체코",
  "Côte d'Ivoire": "코트디부아르",
  "Dem. Rep. Congo": "콩고민주공화국",
  Denmark: "덴마크",
  Djibouti: "지부티",
  "Dominican Rep.": "도미니카공화국",
  Ecuador: "에콰도르",
  Egypt: "이집트",
  "El Salvador": "엘살바도르",
  "Eq. Guinea": "적도기니",
  Eritrea: "에리트레아",
  Estonia: "에스토니아",
  Ethiopia: "에티오피아",
  "Falkland Is.": "포클랜드 제도",
  Fiji: "피지",
  Finland: "핀란드",
  "Fr. S. Antarctic Lands": "프랑스령 남방·남극 지역",
  France: "프랑스",
  Gabon: "가봉",
  Gambia: "감비아",
  Georgia: "조지아",
  Germany: "독일",
  Ghana: "가나",
  Greece: "그리스",
  Greenland: "그린란드",
  Guatemala: "과테말라",
  Guinea: "기니",
  "Guinea-Bissau": "기니비사우",
  Guyana: "가이아나",
  Haiti: "아이티",
  Honduras: "온두라스",
  Hungary: "헝가리",
  Iceland: "아이슬란드",
  India: "인도",
  Indonesia: "인도네시아",
  Iran: "이란",
  Iraq: "이라크",
  Ireland: "아일랜드",
  Israel: "이스라엘",
  Italy: "이탈리아",
  Jamaica: "자메이카",
  Japan: "일본",
  Jordan: "요르단",
  Kazakhstan: "카자흐스탄",
  Kenya: "케냐",
  Kosovo: "코소보",
  Kuwait: "쿠웨이트",
  Kyrgyzstan: "키르기스스탄",
  Laos: "라오스",
  Latvia: "라트비아",
  Lebanon: "레바논",
  Lesotho: "레소토",
  Liberia: "라이베리아",
  Libya: "리비아",
  Lithuania: "리투아니아",
  Luxembourg: "룩셈부르크",
  Macedonia: "북마케도니아",
  Madagascar: "마다가스카르",
  Malawi: "말라위",
  Malaysia: "말레이시아",
  Mali: "말리",
  Mauritania: "모리타니",
  Mexico: "멕시코",
  Moldova: "몰도바",
  Mongolia: "몽골",
  Montenegro: "몬테네그로",
  Morocco: "모로코",
  Mozambique: "모잠비크",
  Myanmar: "미얀마",
  "N. Cyprus": "북키프로스",
  Namibia: "나미비아",
  Nepal: "네팔",
  Netherlands: "네덜란드",
  "New Caledonia": "뉴칼레도니아",
  "New Zealand": "뉴질랜드",
  Nicaragua: "니카라과",
  Niger: "니제르",
  Nigeria: "나이지리아",
  "North Korea": "북한",
  Norway: "노르웨이",
  Oman: "오만",
  Pakistan: "파키스탄",
  Palestine: "팔레스타인",
  Panama: "파나마",
  "Papua New Guinea": "파푸아뉴기니",
  Paraguay: "파라과이",
  Peru: "페루",
  Philippines: "필리핀",
  Poland: "폴란드",
  Portugal: "포르투갈",
  "Puerto Rico": "푸에르토리코",
  Qatar: "카타르",
  Romania: "루마니아",
  Russia: "러시아",
  Rwanda: "르완다",
  "S. Sudan": "남수단",
  "Saudi Arabia": "사우디아라비아",
  Senegal: "세네갈",
  Serbia: "세르비아",
  "Sierra Leone": "시에라리온",
  Slovakia: "슬로바키아",
  Slovenia: "슬로베니아",
  "Solomon Is.": "솔로몬 제도",
  Somalia: "소말리아",
  Somaliland: "소말릴란드",
  "South Africa": "남아프리카공화국",
  "South Korea": "대한민국",
  Spain: "스페인",
  "Sri Lanka": "스리랑카",
  Sudan: "수단",
  Suriname: "수리남",
  Sweden: "스웨덴",
  Switzerland: "스위스",
  Syria: "시리아",
  Taiwan: "타이완",
  Tajikistan: "타지키스탄",
  Tanzania: "탄자니아",
  Thailand: "태국",
  "Timor-Leste": "동티모르",
  Togo: "토고",
  "Trinidad and Tobago": "트리니다드 토바고",
  Tunisia: "튀니지",
  Turkey: "튀르키예",
  Turkmenistan: "투르크메니스탄",
  Uganda: "우간다",
  Ukraine: "우크라이나",
  "United Arab Emirates": "아랍에미리트",
  "United Kingdom": "영국",
  "United States of America": "미국",
  Uruguay: "우루과이",
  Uzbekistan: "우즈베키스탄",
  Vanuatu: "바누아투",
  Venezuela: "베네수엘라",
  Vietnam: "베트남",
  "W. Sahara": "서사하라",
  Yemen: "예멘",
  Zambia: "잠비아",
  Zimbabwe: "짐바브웨",
  eSwatini: "에스와티니",
};

/** 화면 언어에 맞는 나라 이름. 대조표에 없으면 원문 그대로. */
export function localizeCountryName(name: string, locale: string): string {
  if (locale !== "ko") return name;
  return COUNTRY_NAMES_KO[name] ?? name;
}
