import type { FeaturedFaction } from "@/actions/home/getFeaturedFactions";
import type { FactionFigureBook } from "@/actions/home/getFactionFigureBooks";
import { MYTH_OTHER_GROUP_ID, type MythData } from "@/actions/home/mythTypes";
import type { CelebProfile } from "@/types/home";
import type { Locale } from "@/types/locale";
import { buildFactionClusters, localizedFactionDescription, localizedFactionName } from "./faction-sections";

/** 테마 그림만 등록한다. 과거 단체화보는 테마의 대표 이미지로 자동 승격하지 않는다. */
const THEME_ART: Record<string, string> = {
  "2000s-hollywood-action": "/images/factions/themes/2000s-hollywood-action-v2.webp",
  "80s-hollywood-action": "/images/factions/themes/80s-hollywood-action-v2.webp",
  "ai-new-wave": "/images/factions/themes/ai-new-wave-v3.webp",
  "ai-pioneers": "/images/factions/themes/ai-pioneers-v2.webp",
  "aircraft-makers": "/images/factions/themes/aircraft-makers-v3.webp",
  "american-literature-founders": "/images/factions/themes/american-literature-founders-v2.webp",
  "ancient-philosophers": "/images/factions/themes/ancient-philosophers-v3.webp",
  "anthropic": "/images/factions/themes/anthropic-v2.webp",
  "asset-management-empires": "/images/factions/themes/asset-management-empires-v2.webp",
  "autodidact": "/images/factions/themes/autodidact-v3.webp",
  "autonomous-driving": "/images/factions/themes/autonomous-driving-v2.webp",
  "beauty-creators": "/images/factions/themes/beauty-creators-v3.webp",
  "biotech": "/images/factions/themes/biotech-v2.webp",
  "capital-allocators": "/images/factions/themes/capital-allocators-v2.webp",
  "carthage": "/images/factions/themes/carthage-v2.webp",
  "chaebol-owners": "/images/factions/themes/chaebol-owners-v3.webp",
  "chinese-classical-literature": "/images/factions/themes/chinese-classical-literature-v2.webp",
  "chinese-empire": "/images/factions/themes/chinese-empire-v2.webp",
  "chinese-thought": "/images/factions/themes/chinese-thought-v2.webp",
  "christian-thought": "/images/factions/themes/christian-thought-v2.webp",
  "chungmuro": "/images/factions/themes/chungmuro-v3.webp",
  "classical-scholarship": "/images/factions/themes/classical-scholarship-v3.webp",
  "cold-war": "/images/factions/themes/cold-war-v2.webp",
  "comedy-creators": "/images/factions/themes/comedy-creators-v2.webp",
  "comics-masters": "/images/factions/themes/comics-masters-v2.webp",
  "community-platforms": "/images/factions/themes/community-platforms-v2.webp",
  "conquerors": "/images/factions/themes/conquerors-v2.webp",
  "console-wars": "/images/factions/themes/console-wars-v3.webp",
  "credit-and-central-banks": "/images/factions/themes/credit-and-central-banks-v2.webp",
  "cybersecurity": "/images/factions/themes/cybersecurity-v2.webp",
  "dawn-of-rome": "/images/factions/themes/dawn-of-rome-v2.webp",
  "defense-industry": "/images/factions/themes/defense-industry-v2.webp",
  "deprivation": "/images/factions/themes/deprivation-v2.webp",
  "digital-gold-rush": "/images/factions/themes/digital-gold-rush-v2.webp",
  "digital-resistance": "/images/factions/themes/digital-resistance-v2.webp",
  "discovery-of-evolution": "/images/factions/themes/discovery-of-evolution-v2.webp",
  "discovery-of-the-atom": "/images/factions/themes/discovery-of-the-atom-v3.webp",
  "drone-makers": "/images/factions/themes/drone-makers-v2.webp",
  "early-console-wars": "/images/factions/themes/early-console-wars-v2.webp",
  "east-asia-enlightenment": "/images/factions/themes/east-asia-enlightenment-v2.webp",
  "east-asian-buddhism": "/images/factions/themes/east-asian-buddhism-v3.webp",
  "energy-cartel": "/images/factions/themes/energy-cartel-v2.webp",
  "ev-and-battery": "/images/factions/themes/ev-and-battery-v2.webp",
  "exiles": "/images/factions/themes/exiles-v3.webp",
  "existentialists": "/images/factions/themes/existentialists-v3.webp",
  "fast-food-empire": "/images/factions/themes/fast-food-empire-v2.webp",
  "fighting-arts": "/images/factions/themes/fighting-arts-v2.webp",
  "film-directors": "/images/factions/themes/film-directors-v2.webp",
  "fin-de-si-cle-vienna": "/images/factions/themes/fin-de-si-cle-vienna-v2.webp",
  "football-managers": "/images/factions/themes/football-managers-v2.webp",
  "founding-monarchs": "/images/factions/themes/founding-monarchs-v3.webp",
  "french-empire": "/images/factions/themes/french-empire-v2.webp",
  "french-novelists": "/images/factions/themes/french-novelists-v2.webp",
  "game-empire": "/images/factions/themes/game-empire-v2.webp",
  "gaming-creators": "/images/factions/themes/gaming-creators-v3.webp",
  "genre-cinema": "/images/factions/themes/genre-cinema-v2.webp",
  "google-deepmind": "/images/factions/themes/google-deepmind-v3.webp",
  "great-hackers-faces": "/images/factions/themes/great-hackers-faces-v2.webp",
  "hip-hop-and-rnb": "/images/factions/themes/hip-hop-and-rnb-v2.webp",
  "hollywood-golden-age": "/images/factions/themes/hollywood-golden-age-v2.webp",
  "home-computer-wars": "/images/factions/themes/home-computer-wars-v2.webp",
  "hong-gildong-jeon": "/images/factions/themes/hong-gildong-jeon-v2.webp",
  "hong-kong-cinema": "/images/factions/themes/hong-kong-cinema-v2.webp",
  "humanoid-robotics": "/images/factions/themes/humanoid-robotics-v2.webp",
  "hundred-schools-of-thought": "/images/factions/themes/hundred-schools-of-thought-v2.webp",
  "hybe": "/images/factions/themes/hybe-v2.webp",
  "idol-group-current-female": "/images/factions/themes/idol-group-current-female-v2.webp",
  "idol-group-current-male": "/images/factions/themes/idol-group-current-male-v2.webp",
  "idol-group-former-female": "/images/factions/themes/idol-group-former-female-v3.webp",
  "idol-group-former-male": "/images/factions/themes/idol-group-former-male-v3.webp",
  "im-kkeokjeong": "/images/factions/themes/im-kkeokjeong-v3.webp",
  "immortality-seekers": "/images/factions/themes/immortality-seekers-v2.webp",
  "islamic-thought": "/images/factions/themes/islamic-thought-v2.webp",
  "jang-gilsan": "/images/factions/themes/jang-gilsan-v3.webp",
  "jazz-and-soul": "/images/factions/themes/jazz-and-soul-v2.webp",
  "joseon-dynasty": "/images/factions/themes/joseon-dynasty-v2.webp",
  "joseon-scholars": "/images/factions/themes/joseon-scholars-v2.webp",
  "jyp-entertainment": "/images/factions/themes/jyp-entertainment-v2.webp",
  "knowledge-youtubers": "/images/factions/themes/knowledge-youtubers-v4.webp",
  "korea-football-best11": "/images/factions/themes/korea-football-best11-v3.webp",
  "korea-sports-legends": "/images/factions/themes/korea-sports-legends-v2.webp",
  "korean-art": "/images/factions/themes/korean-art-v2.webp",
  "korean-cinema": "/images/factions/themes/korean-cinema-v2.webp",
  "korean-drama": "/images/factions/themes/korean-drama-v2.webp",
  "korean-literature": "/images/factions/themes/korean-literature-v2.webp",
  "late-han-warlords": "/images/factions/themes/late-han-warlords-v2.webp",
  "latin-music": "/images/factions/themes/latin-music-v2.webp",
  "left-and-right": "/images/factions/themes/left-and-right-v2.webp",
  "legendary-pirates": "/images/factions/themes/legendary-pirates-v2.webp",
  "lineage-of-mathematics": "/images/factions/themes/lineage-of-mathematics-v3.webp",
  "lineage-of-medicine": "/images/factions/themes/lineage-of-medicine-v2.webp",
  "literary-masters": "/images/factions/themes/literary-masters-v2.webp",
  "logistics-empire": "/images/factions/themes/logistics-empire-v2.webp",
  "lone-conquerors": "/images/factions/themes/lone-conquerors-v2.webp",
  "lord-of-the-rings": "/images/factions/themes/lord-of-the-rings-v2.webp",
  "luxury-empire": "/images/factions/themes/luxury-empire-v2.webp",
  "macedonian-empire": "/images/factions/themes/macedonian-empire-v2.webp",
  "maestro": "/images/factions/themes/maestro-v3.webp",
  "mafia": "/images/factions/themes/mafia-v2.webp",
  "magicians": "/images/factions/themes/magicians-v2.webp",
  "manhattan-project": "/images/factions/themes/manhattan-project-v2.webp",
  "masked-hackers": "/images/factions/themes/masked-hackers-v2.webp",
  "masters-of-painting": "/images/factions/themes/masters-of-painting-v2.webp",
  "mcu": "/images/factions/themes/mcu-v2.webp",
  "media-empires": "/images/factions/themes/media-empires-v2.webp",
  "messengers": "/images/factions/themes/messengers-v4.webp",
  "meta": "/images/factions/themes/meta-v3.webp",
  "method-acting": "/images/factions/themes/method-acting-v2.webp",
  "mlb": "/images/factions/themes/mlb-v2.webp",
  "modern-architects": "/images/factions/themes/modern-architects-v2.webp",
  "modern-management-thinkers": "/images/factions/themes/modern-management-thinkers-v3.webp",
  "modern-philosophers": "/images/factions/themes/modern-philosophers-v2.webp",
  "modern-poetry-pioneers": "/images/factions/themes/modern-poetry-pioneers-v3.webp",
  "mongol-empire": "/images/factions/themes/mongol-empire-v2.webp",
  "movie-star-era": "/images/factions/themes/movie-star-era-v2.webp",
  "music-streaming-wars": "/images/factions/themes/music-streaming-wars-v3.webp",
  "musk-inner-court": "/images/factions/themes/musk-inner-court-v3.webp",
  "nba": "/images/factions/themes/nba-v2.webp",
  "new-hollywood": "/images/factions/themes/new-hollywood-v4.webp",
  "new-space-age": "/images/factions/themes/new-space-age-v3.webp",
  "next-gen-energy": "/images/factions/themes/next-gen-energy-v2.webp",
  "nolan-troupe": "/images/factions/themes/nolan-troupe-v4.webp",
  "nonviolent-resistance": "/images/factions/themes/nonviolent-resistance-v2.webp",
  "openai": "/images/factions/themes/openai-v4.webp",
  "ottoman-empire": "/images/factions/themes/ottoman-empire-v2.webp",
  "payment-networks": "/images/factions/themes/payment-networks-v4.webp",
  "paypal-mafia": "/images/factions/themes/paypal-mafia-v3.webp",
  "pga-tour": "/images/factions/themes/pga-tour-v2.webp",
  "podcasters": "/images/factions/themes/podcasters-v2.webp",
  "pop-legends": "/images/factions/themes/pop-legends-v2.webp",
  "pop-stars-21c": "/images/factions/themes/pop-stars-21c-v3.webp",
  "qin-empire": "/images/factions/themes/qin-empire-v2.webp",
  "quant-empire": "/images/factions/themes/quant-empire-v3.webp",
  "quantum-computing": "/images/factions/themes/quantum-computing-v2.webp",
  "readers-on-the-throne": "/images/factions/themes/readers-on-the-throne-v2.webp",
  "renaissance-maestros": "/images/factions/themes/renaissance-maestros-v3.webp",
  "retail-and-commerce": "/images/factions/themes/retail-and-commerce-v2.webp",
  "revolutionaries": "/images/factions/themes/revolutionaries-v3.webp",
  "road-to-space": "/images/factions/themes/road-to-space-v2.webp",
  "rock-legends": "/images/factions/themes/rock-legends-v2.webp",
  "roman-emperors": "/images/factions/themes/roman-emperors-v2.webp",
  "romantic-comedy": "/images/factions/themes/romantic-comedy-v3.webp",
  "romantic-music": "/images/factions/themes/romantic-music-v3.webp",
  "romes-adversaries": "/images/factions/themes/romes-adversaries-v2.webp",
  "self-made": "/images/factions/themes/self-made-v3.webp",
  "sengoku-warlords": "/images/factions/themes/sengoku-warlords-v2.webp",
  "shakespeare-stage-actors": "/images/factions/themes/shakespeare-stage-actors-v2.webp",
  "sharing-economy": "/images/factions/themes/sharing-economy-v4.webp",
  "silicon-empire": "/images/factions/themes/silicon-empire-v2.webp",
  "sm-entertainment": "/images/factions/themes/sm-entertainment-v3.webp",
  "social-media": "/images/factions/themes/social-media-v3.webp",
  "south-korean-presidents": "/images/factions/themes/south-korean-presidents-v2.webp",
  "spacex": "/images/factions/themes/spacex-v2.webp",
  "special-forces": "/images/factions/themes/special-forces-v2.webp",
  "sports-empire": "/images/factions/themes/sports-empire-v4.webp",
  "spymasters": "/images/factions/themes/spymasters-v3.webp",
  "state-hackers": "/images/factions/themes/state-hackers-v2.webp",
  "stock-exchanges": "/images/factions/themes/stock-exchanges-v2.webp",
  "streaming-empire": "/images/factions/themes/streaming-empire-v3.webp",
  "street-fashion": "/images/factions/themes/street-fashion-v2.webp",
  "tarantino-troupe": "/images/factions/themes/tarantino-troupe-v2.webp",
  "tesla": "/images/factions/themes/tesla-v2.webp",
  "the-chu-han-contention": "/images/factions/themes/the-chu-han-contention-v3.webp",
  "the-founding-fathers": "/images/factions/themes/the-founding-fathers-v2.webp",
  "the-french-revolution": "/images/factions/themes/the-french-revolution-v2.webp",
  "the-lost-generation": "/images/factions/themes/the-lost-generation-v2.webp",
  "the-singularity-is-near": "/images/factions/themes/the-singularity-is-near-v2.webp",
  "thiel-universe": "/images/factions/themes/thiel-universe-v3.webp",
  "thinking-machines": "/images/factions/themes/thinking-machines-v2.webp",
  "three-kingdoms": "/images/factions/themes/three-kingdoms-v2.webp",
  "trump-dynasty": "/images/factions/themes/trump-dynasty-v2.webp",
  "us-presidents": "/images/factions/themes/us-presidents-v3.webp",
  "vlog": "/images/factions/themes/vlog-v2.webp",
  "wall-street": "/images/factions/themes/wall-street-v2.webp",
  "warring-states": "/images/factions/themes/warring-states-v2.webp",
  "wild-west": "/images/factions/themes/wild-west-v2.webp",
  "world-cup-2026": "/images/factions/themes/world-cup-2026-v2.webp",
  "world-football-best11": "/images/factions/themes/world-football-best11-v2.webp",
  "ww2-asia-pacific": "/images/factions/themes/ww2-asia-pacific-v2.webp",
  "ww2-axis-europe": "/images/factions/themes/ww2-axis-europe-v2.webp",
  "ww2-britain-free-france": "/images/factions/themes/ww2-britain-free-france-v2.webp",
  "ww2-soviet-union": "/images/factions/themes/ww2-soviet-union-v2.webp",
  "ww2-united-states": "/images/factions/themes/ww2-united-states-v2.webp",
  "x-men": "/images/factions/themes/x-men-v2.webp",
  "x-platform": "/images/factions/themes/x-platform-v2.webp",
  "xai": "/images/factions/themes/xai-v2.webp",
  "yg-theblacklabel": "/images/factions/themes/yg-theblacklabel-v2.webp",
  "youtube-stars": "/images/factions/themes/youtube-stars-v4.webp",
};

export function getFactionThemeImage(slug: string | null): string | undefined {
  return slug ? THEME_ART[slug] : undefined;
}

export interface FactionThemeGroup {
  name: string;
  description: string | null;
  description_en: string | null;
}

/** 현재 테마 한 개만 공용 탐색판에 전달한다. 다른 테마는 기존의 정식 주소로 이동한다. */
export function toFactionThemeData(entry: FeaturedFaction, celebs: CelebProfile[], groupRows: FactionThemeGroup[], books: FactionFigureBook[], locale: Locale): MythData {
  const isEn = locale === "en";
  const byId = new Map(celebs.map((person) => [person.id, person]));
  const members = entry.celebs.filter((member) => byId.has(member.id));
  const personIds = members.map((member) => member.id);
  const descriptions = new Map(groupRows.map((group) => [group.name, (isEn ? group.description_en : group.description)?.trim() || null]));
  const clusters = buildFactionClusters(members, locale);
  const slug = entry.slug ?? entry.id;
  const image = getFactionThemeImage(slug);
  const theme = {
    id: entry.id, slug, name: localizedFactionName(entry, locale),
    description: localizedFactionDescription(entry, locale),
    isPublished: true, regionId: "faction", music: entry.music,
    images: image ? [{ url: image, label: null }] : [],
    personIds, leadPersonIds: [],
    groups: clusters.length > 1 ? clusters.map((cluster) => ({
      id: cluster.name ?? MYTH_OTHER_GROUP_ID, name: cluster.label,
      description: cluster.name ? descriptions.get(cluster.name) ?? null : null,
      personIds: cluster.celebIds,
    })) : [],
  };
  return {
    openingPersonId: null,
    regions: [{ id: "faction", slug: "faction", name: theme.name, mythIds: [entry.id] }],
    myths: [theme],
    people: members.map((member) => {
      const person = byId.get(member.id)!;
      const summary = (isEn ? member.short_desc_en : member.short_desc)?.trim() || null;
      return {
        id: person.id, slug: person.slug ?? person.id,
        name: isEn ? person.nickname_en || person.nickname : person.nickname,
        reality: person.celeb_reality,
        title: isEn ? person.title_en || person.title : person.title,
        headline: null, bio: isEn ? person.bio_en : person.bio, reading: null, summary,
        appearances: [{ mythId: entry.id, summary, imageUrl: member.faction_image_url }],
        avatarUrl: person.avatar_url, imageUrl: null, portraitUrl: member.portrait_url ?? null, images: [],
        mythIds: [entry.id], sourceIds: books.filter((book) => book.memberIds.includes(person.id)).map((book) => book.contentId),
      };
    }),
    works: books.map((book) => ({
      id: book.contentId, editionId: book.editionId,
      title: book.title, titleBadge: book.titleBadge ?? null,
      creator: book.creator ?? null, thumbnailUrl: book.thumbnail ?? null,
      category: "book", coupangUrl: isEn ? null : book.url || null,
      personIds: book.memberIds,
    })),
  };
}
