import { ISBN10_PATTERN, ISBN13_PATTERN, ISBN10_WEIGHTS, ISBN13_WEIGHTS, ISBN_FORMATTING_PATTERN } from './book-isbn'

// PostgreSQL의 [:space:]는 NBSP·BOM을 포함하지 않아 같은 JS 정규식으로 문자 집합을 만든다.
const formatting = new RegExp(ISBN_FORMATTING_PATTERN.source)
const formattingCodePoints = Array.from({ length: 0x10000 }, (_, code) => code)
  .filter(code => code !== 45 && formatting.test(String.fromCharCode(code)))
formattingCodePoints.push(45) // 정규식 문자 클래스에서 하이픈은 마지막에 둔다.
const formattingSql = `U&'[${formattingCodePoints.map(code => `\\${code.toString(16).padStart(4, '0')}`).join('')}]'`

// 기존 DB 컬럼의 CHECK도 검색·화면과 같은 ISBN 패턴 및 체크 숫자를 사용한다.
export function isbnSqlCheck(column: string): string {
  if (!/^[a-z_][a-z0-9_]*$/.test(column)) throw new Error('Invalid SQL column name')
  const field = `"${column}"`
  const compact = `upper(regexp_replace(coalesce(${field}, ''), ${formattingSql}, '', 'g'))`
  const pattern = (value: RegExp) => value.source.replaceAll('[\\dX]', '[0-9X]').replaceAll('\\d', '[0-9]')
  const sum = (weights: readonly number[], isbn10: boolean) => weights.map((weight, index) => {
    const digit = `substring(${compact} from ${index + 1} for 1)`
    const value = isbn10 && index === 9 ? `(CASE WHEN ${digit} = 'X' THEN 10 ELSE ${digit}::integer END)` : `${digit}::integer`
    return `(${value} * ${weight})`
  }).join(' + ')
  return `${field} IS NULL OR ${compact} = '' OR CASE\n`
    + `  WHEN ${compact} ~ '${pattern(ISBN13_PATTERN)}' THEN (${sum(ISBN13_WEIGHTS, false)}) % 10 = 0\n`
    + `  WHEN ${compact} ~ '${pattern(ISBN10_PATTERN)}' THEN (${sum(ISBN10_WEIGHTS, true)}) % 11 = 0\n`
    + '  ELSE false\nEND'
}

export function contentIsbnMigration(): string {
  const check = isbnSqlCheck('isbn')
  const tables = ['content_locales', 'figure_book_editions']
  return '-- Generated by scripts/oracle-db/content-isbn-check.ts; edit the shared ISBN contract, not this expression.\n'
    + 'BEGIN;\nSET LOCAL lock_timeout = \'5s\';\nSET LOCAL statement_timeout = \'30s\';\n'
    + tables.map(table => `ALTER TABLE public.${table} ADD CONSTRAINT ${table}_isbn_valid CHECK (${check}) NOT VALID;\n`).join('')
    + tables.map(table => `ALTER TABLE public.${table} VALIDATE CONSTRAINT ${table}_isbn_valid;\n`).join('')
    + 'COMMIT;\n'
}
