import { useState, useEffect, useCallback, useMemo } from 'react'
import {
  buildTitle, buildDescription, calcChapterTimestamps,
  type EpisodeMeta, type YouTubeLink,
} from '@feelandnote/shared/lib/youtube-meta'
import type { YouTubeStatus, EpisodeData, VariantKey, MetaEntry } from './types'
import { parseVariantKey, buildVariantKeys } from './utils'

export function useYouTubePanel(series: string, name: string) {
  const [status, setStatus] = useState<YouTubeStatus | null>(null)
  const [loading, setLoading] = useState(true)
  const [epKo, setEpKo] = useState<EpisodeData | null>(null)
  const [epEn, setEpEn] = useState<EpisodeData | null>(null)
  const [dryRun, setDryRun] = useState(false)
  const [uploadMsg, setUploadMsg] = useState<string | null>(null)
  const [uploadLog, setUploadLog] = useState<string[] | null>(null)
  const [uploadTaskId, setUploadTaskId] = useState<string | null>(null)
  const [uploadActive, setUploadActive] = useState(false)
  const [openVariant, setOpenVariant] = useState<VariantKey | null>(null)
  const [editMeta, setEditMeta] = useState<Record<VariantKey, MetaEntry>>({} as any)
  const [editingLineup, setEditingLineup] = useState(false)
  const [lineupDraft, setLineupDraft] = useState<EpisodeMeta | null>(null)
  const [saving, setSaving] = useState(false)

  // EN 페이지에서도 base name으로 YouTube API 호출
  // alex-karp-en → alex-karp, alex-karp-2-en → alex-karp-2 (번호 suffix는 보존되어 alt 에피소드 구분)
  const baseName = name.endsWith('-en') ? name.slice(0, -3) : name

  // --- 데이터 로드 ---

  const fetchStatus = useCallback(() => {
    setLoading(true)
    fetch(`/api/${series}/youtube/status?episode=${baseName}`)
      .then(r => r.json())
      .then(setStatus)
      .catch(() => {})
      .finally(() => setLoading(false))
  }, [series, baseName])

  useEffect(() => { fetchStatus() }, [fetchStatus])

  useEffect(() => {
    fetch(`/api/${series}/episodes/${baseName}`)
      .then(r => r.ok ? r.json() : null)
      .then(setEpKo)
      .catch(() => {})
    fetch(`/api/${series}/episodes/${baseName}-en`)
      .then(r => r.ok ? r.json() : null)
      .then(setEpEn)
      .catch(() => {})
  }, [series, baseName])

  // --- 노출 variant 키 (shorts 배열 길이 기반 동적 생성) ---

  const visibleVariantKeys = useMemo<VariantKey[]>(
    () => buildVariantKeys(epKo, epEn),
    [epKo, epEn],
  )

  // --- 자동 생성 값 ---

  const autoGenerated = useMemo(() => {
    const result: Record<VariantKey, MetaEntry> = {}
    const lineupMeta = status?.lineup

    for (const key of visibleVariantKeys) {
      const { lang, type, shortsIndex } = parseVariantKey(key)
      const ep = lang === 'ko' ? epKo : epEn
      if (!ep) continue

      const celebName = lang === 'ko' ? ep.host.nickname : (ep.host.nickname_en ?? ep.host.nickname)
      const isShorts = type === 'shorts'
      // shortsIndex 1-based. 배열 접근 시 -1.
      const shortsCfg = isShorts ? ep.shorts?.[shortsIndex - 1] : undefined
      const shortsBookTitle = isShorts
        ? (shortsCfg?.featuredBookIndex !== undefined
            ? ep.books?.[shortsCfg.featuredBookIndex]?.title
            : ep.books?.[0]?.title)
        : undefined
      // 롱폼 신규 포맷에 필요한 책 수 / 부 번호.
      // 다부 에피소드(series.totalParts > 1)는 totalBooks + part 사용, 단일 부는 books.length.
      const isMultipart = (ep.series?.totalParts ?? 1) > 1
      const longformBookCount = isMultipart ? (ep.series?.totalBooks ?? ep.books.length) : ep.books.length
      const longformPart = isMultipart ? ep.series?.part : undefined
      // lineupMeta 유무와 무관하게 신규 롱폼 포맷은 항상 계산 가능 — 빈 meta 폴백으로 buildTitle 호출.
      const titleMeta = lineupMeta ?? {}
      const title = buildTitle(titleMeta, celebName, lang, isShorts, shortsIndex, shortsBookTitle, longformBookCount, longformPart)

      let chapters: { time: string; label: string }[] | undefined
      if (!isShorts) {
        try { chapters = calcChapterTimestamps(ep, lang) } catch { /* fallback */ }
      }

      const featuredBookIndex = isShorts ? (shortsCfg?.featuredBookIndex ?? 0) : undefined
      const description = buildDescription(celebName, ep.books, lang, isShorts, chapters, undefined, baseName, shortsIndex, featuredBookIndex)
      result[key] = { title, description, links: [] }
    }
    return result
  }, [status?.lineup, epKo, epEn, visibleVariantKeys, baseName])

  // editMeta 초기화: meta 있으면 override, 없으면 autoGenerated
  useEffect(() => {
    const merged: Record<VariantKey, MetaEntry> = {}
    for (const key of visibleVariantKeys) {
      const auto = autoGenerated[key]
      const saved = status?.meta?.[key]
      merged[key] = {
        title: saved?.title ?? auto?.title ?? '',
        description: saved?.description ?? auto?.description ?? '',
        links: saved?.links ?? [],
      }
    }
    setEditMeta(merged)
  }, [autoGenerated, status?.meta, visibleVariantKeys])

  // --- 이벤트 핸들러 ---

  const saveMeta = async () => {
    await fetch(`/api/${series}/youtube/meta?episode=${baseName}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(editMeta),
    })
  }

  const handleUpload = async (lang?: string, type?: string, shortsIndex?: number, bookIndex?: number) => {
    // shortsIndex 1-based. 단일 쇼츠(1)이면 레이블 숫자 생략.
    const idxLabel = (type === 'shorts' && shortsIndex != null && shortsIndex > 1) ? ` #${shortsIndex}` : ''
    const soloLabel = (type === 'solo' && typeof bookIndex === 'number') ? ` B${String(bookIndex + 1).padStart(2, '0')}` : ''
    const label = [lang?.toUpperCase(), type].filter(Boolean).join(' ') + idxLabel + soloLabel || '전체'
    setUploadMsg(`${label} 메타 저장 중...`)
    setUploadLog(null)

    // 업로드 전 메타 자동 저장
    await saveMeta()

    setUploadMsg(`${label} ${dryRun ? '드라이런' : '업로드'} 요청 중...`)

    const res = await fetch(`/api/${series}/youtube/upload`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ episode: baseName, lang, type, shortsIndex, bookIndex, dry: dryRun }),
    })
    if (!res.ok) {
      const err = await res.json().catch(() => ({ error: res.statusText }))
      setUploadMsg(`실패: ${err.error ?? res.statusText}`)
      return
    }

    const { taskId } = await res.json()
    setUploadTaskId(taskId)
    setUploadActive(true)
    setUploadMsg(`${label} ${dryRun ? '드라이런' : '업로드'} 진행 중...`)

    // 태스크 직접 폴링
    const poll = setInterval(async () => {
      try {
        const tr = await fetch(`/api/tasks/${taskId}`)
        if (!tr.ok) return
        const task = await tr.json()
        setUploadLog(task.log?.slice(-20) ?? [])
        if (task.status !== 'running' && task.status !== 'queued') {
          clearInterval(poll)
          setUploadActive(false)
          setUploadTaskId(null)
          if (task.status === 'done') setUploadMsg(`${label} ${dryRun ? '드라이런' : '업로드'} 완료`)
          else if (task.status === 'cancelled') setUploadMsg(`${label} 업로드 중단됨`)
          else setUploadMsg(`${label} 오류 발생`)
        }
      } catch { /* ignore */ }
    }, 1500)
  }

  const handleCancelUpload = async () => {
    if (!uploadTaskId) return
    await fetch(`/api/${series}/youtube/upload?taskId=${uploadTaskId}`, { method: 'DELETE' })
  }

  const handleSaveMeta = async () => {
    setSaving(true)
    try {
      await saveMeta()
      fetchStatus()
    } finally { setSaving(false) }
  }

  const handleDbSync = async () => {
    setUploadMsg('DB 투입 중...')
    setUploadLog(null)
    try {
      const res = await fetch(`/api/${series}/youtube/db-sync?episode=${baseName}`, { method: 'POST' })
      const data = await res.json()
      if (!res.ok) {
        setUploadMsg(`DB 투입 실패: ${data.error ?? res.statusText}`)
        return
      }
      setUploadMsg(`DB 투입 완료: ${data.slug} (${data.variantCount}개 variant)`)
    } catch (e) {
      setUploadMsg(`DB 투입 오류: ${e instanceof Error ? e.message : String(e)}`)
    }
  }

  const handleResetVariant = (key: VariantKey) => {
    const auto = autoGenerated[key]
    if (!auto) return
    setEditMeta(prev => ({ ...prev, [key]: { ...auto } }))
  }

  const handleSaveLineup = async () => {
    if (!lineupDraft) return
    setSaving(true)
    try {
      await fetch(`/api/${series}/youtube/lineup?episode=${baseName}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(lineupDraft),
      })
      setEditingLineup(false)
      fetchStatus()
    } finally { setSaving(false) }
  }

  const updateMeta = (key: VariantKey, field: 'title' | 'description', value: string) => {
    setEditMeta(prev => ({ ...prev, [key]: { ...prev[key], [field]: value } }))
  }

  const updateLinks = (key: VariantKey, links: YouTubeLink[]) => {
    setEditMeta(prev => ({ ...prev, [key]: { ...prev[key], links } }))
  }

  return {
    status, loading, epKo, epEn,
    dryRun, setDryRun,
    uploadMsg, uploadLog, uploadActive,
    openVariant, setOpenVariant,
    editMeta, setEditMeta,
    editingLineup, setEditingLineup,
    lineupDraft, setLineupDraft,
    saving,
    visibleVariantKeys,
    fetchStatus,
    handleUpload, handleCancelUpload, handleSaveMeta,
    handleDbSync, handleResetVariant, handleSaveLineup,
    updateMeta, updateLinks,
  }
}
