/** 로컬 PostgreSQL만 사용한다. PG_TEST_BIN 없이는 운영 DB로 대체하지 않는다. */
import test from 'node:test'
import assert from 'node:assert/strict'
import { existsSync, mkdtempSync, readFileSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { basename, join, resolve } from 'node:path'
import { spawn, spawnSync } from 'node:child_process'
import { createServer } from 'node:net'
import { CONTENT_ARRAY_REFERENCES } from './lib/content-array-references.mjs'
import { buildMergeSql, SNAPSHOT_TABLES } from './lib/merge-work-sql.mjs'
import { contentArrayReferenceMigration } from '../../../../scripts/oracle-db/content-array-reference.mjs'

const migration = contentArrayReferenceMigration()
test('저장된 migration과 공통 배열 계약의 생성 결과가 같다', () => {
  assert.equal(readFileSync(new URL('../../../web/database/migrations/20261002000002_content_array_reference.sql', import.meta.url), 'utf8'), migration)
})

const bin = process.env.PG_TEST_BIN
const executable = name => join(bin, name + (process.platform === 'win32' ? '.exe' : ''))
const referenceValue = ref => ref.shape === 'tiers' ? `'{"S":["drop"]}'::jsonb`
  : ref.storage === 'jsonb' ? `'["drop"]'::jsonb` : `ARRAY['drop']::text[]`
const createReference = ref => `INSERT INTO ${ref.table}(id${ref.table === 'flow_nodes' ? ',content_id' : ''},${ref.column}) VALUES('reference'${ref.table === 'flow_nodes' ? ",'other'" : ''},${referenceValue(ref)});`
const schema = `
CREATE TABLE contents(id text PRIMARY KEY,type text,external_id text,member_count int DEFAULT 0,celeb_count int DEFAULT 0,record_count int DEFAULT 0,release_date text,metadata jsonb);
CREATE TABLE content_locales(content_id text REFERENCES contents ON DELETE CASCADE,locale text,title text,creator text,description text,isbn text,publisher text,thumbnail_url text,verified bool,sources jsonb,PRIMARY KEY(content_id,locale));
CREATE TABLE figure_book_contents(content_id text PRIMARY KEY REFERENCES contents ON DELETE RESTRICT);
CREATE TABLE figure_book_characters(content_id text REFERENCES figure_book_contents ON DELETE CASCADE,celeb_id text,relation_type text,description text,description_en text,PRIMARY KEY(content_id,celeb_id));
CREATE TABLE figure_book_editions(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,content_id text REFERENCES figure_book_contents ON DELETE CASCADE,locale text,title text,creator text,description text,isbn text,publisher text,thumbnail_url text,release_date date,edition_kind text,text_scope text,sort_order int,verified bool,sources jsonb);
CREATE UNIQUE INDEX edition_isbn ON figure_book_editions(content_id,locale,isbn) WHERE isbn IS NOT NULL;
CREATE TABLE figure_book_products(id bigint PRIMARY KEY,edition_id bigint REFERENCES figure_book_editions ON DELETE CASCADE,platform text,is_active bool);
CREATE TABLE member_contents(id text PRIMARY KEY,content_id text REFERENCES contents ON DELETE CASCADE,member_id text,review text,rating int,UNIQUE(member_id,content_id));
CREATE TABLE celeb_contents(id text PRIMARY KEY,content_id text REFERENCES contents ON DELETE CASCADE,celeb_id text,review text,review_en text,source_url text,UNIQUE(celeb_id,content_id));
CREATE TABLE curated_list_items(id text PRIMARY KEY,content_id text REFERENCES contents ON DELETE SET NULL,list_id text,rank int,sort_order int,raw_title text,note text);
CREATE TABLE flow_nodes(id text PRIMARY KEY,content_id text REFERENCES contents ON DELETE CASCADE,bonus_content_ids jsonb);
CREATE TABLE records(id text PRIMARY KEY,content_id text REFERENCES contents ON DELETE CASCADE,body text);
CREATE TABLE notes(id text PRIMARY KEY,content_id text REFERENCES contents ON DELETE CASCADE,memo text);
CREATE TABLE activity_logs(id text PRIMARY KEY,content_id text REFERENCES contents ON DELETE SET NULL,metadata jsonb);
CREATE TABLE faction_lv2(id text PRIMARY KEY,theme_book_ids text[]);
CREATE TABLE flows(id text PRIMARY KEY,tiers jsonb);
CREATE TABLE tier_lists(id text PRIMARY KEY,tiers jsonb,unranked text[]);
`

test('실제 PostgreSQL에서 배열 참조 삭제·입력·통합과 동시 저장을 방어한다', {
  skip: !bin && 'PG_TEST_BIN을 로컬 PostgreSQL bin 경로로 지정하세요', timeout: 120000,
}, async t => {
  assert.ok(existsSync(executable('initdb')))
  const directory = mkdtempSync(join(tmpdir(), 'feelandnote-array-reference-test-'))
  const data = join(directory, 'db')
  const run = (name, args, input, options = {}) => {
    const result = spawnSync(executable(name), args, { input, encoding: 'utf8', windowsHide: true, shell: false, timeout: 15000, maxBuffer: 10 * 1024 * 1024, ...options })
    if (result.error || result.status !== 0) throw new Error(result.error?.message ?? result.stderr)
    return result.stdout?.trim() ?? ''
  }
  const server = createServer()
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve))
  const port = server.address().port
  await new Promise(resolve => server.close(resolve))
  let started = false
  const clients = new Set()
  t.after(() => {
    for (const client of clients) client.kill()
    if (started) run('pg_ctl', ['-D', data, '-m', 'immediate', '-w', 'stop'])
    assert.ok(resolve(directory).startsWith(resolve(tmpdir()) + (process.platform === 'win32' ? '\\' : '/')) && basename(directory).startsWith('feelandnote-array-reference-test-'))
    if (process.platform === 'win32') {
      const result = spawnSync('powershell', ['-NoProfile', '-Command', `Remove-Item -LiteralPath '${directory.replaceAll("'", "''")}' -Recurse`], { windowsHide: true, shell: false, encoding: 'utf8' })
      assert.equal(result.status, 0, result.stderr)
    } else rmSync(directory, { recursive: true })
  })
  run('initdb', ['-D', data, '-U', 'postgres', '-A', 'trust', '--no-locale', '--encoding=UTF8'])
  started = true
  run('pg_ctl', ['-D', data, '-l', join(directory, 'postgres.log'), '-o', `-h 127.0.0.1 -p ${port}`, '-w', 'start'], undefined, { stdio: 'ignore' })
  const args = ['-X', '-qAt', '-v', 'ON_ERROR_STOP=1', '-v', 'VERBOSITY=verbose', '-h', '127.0.0.1', '-p', String(port), '-U', 'postgres', '-d', 'postgres']
  const query = sql => run('psql', args, sql)
  const reset = extra => query(`TRUNCATE ${SNAPSHOT_TABLES.join(',')} RESTART IDENTITY CASCADE; INSERT INTO contents(id,type) VALUES('keep','BOOK'),('drop','BOOK'),('other','BOOK'); ${extra ?? ''}`)
  const snapshot = () => JSON.parse(query(`SELECT jsonb_build_object(${SNAPSHOT_TABLES.map(table => `'${table}',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM ${table} t)`).join(',')});`))
  const orphanCount = () => query(`SELECT ${CONTENT_ARRAY_REFERENCES.map(ref => `(SELECT count(*) FROM ${ref.table} t CROSS JOIN LATERAL public.content_array_reference_ids(to_jsonb(t.${ref.column}),'${ref.shape}') r(id) LEFT JOIN contents c ON c.id=r.id WHERE c.id IS NULL)`).join(' + ')};`)
  const waitFor = async predicate => {
    const deadline = Date.now() + 10000
    while (!predicate()) {
      if (Date.now() > deadline) throw new Error('local concurrent PostgreSQL step timed out')
      await new Promise(resolve => setTimeout(resolve, 25))
    }
  }
  const startClient = (name, sql) => {
    const child = spawn(executable('psql'), args, { encoding: 'utf8', windowsHide: true, shell: false, env: { ...process.env, PGAPPNAME: name } })
    clients.add(child)
    const client = { child, stdout: '', stderr: '' }
    child.stdout.setEncoding('utf8'); child.stderr.setEncoding('utf8')
    child.stdout.on('data', text => { client.stdout += text })
    child.stderr.on('data', text => { client.stderr += text })
    client.done = new Promise(resolve => child.on('close', status => { clients.delete(child); resolve({ status, stdout: client.stdout, stderr: client.stderr }) }))
    child.stdin.write(sql + '\n')
    return client
  }
  const finish = async (client, sql = 'COMMIT;') => {
    client.child.stdin.end(sql + '\n')
    return await client.done
  }
  const waiting = name => query(`SELECT count(*) FROM pg_stat_activity WHERE application_name='${name}' AND wait_event_type='Lock';`) === '1'

  query(schema)
  await t.test('적용 전 누락 참조가 있으면 migration 전체를 되돌린다', () => {
    reset(`INSERT INTO faction_lv2 VALUES('invalid',ARRAY['missing']);`)
    assert.throws(() => query(migration), /23503.*existing missing content in faction_lv2.theme_book_ids/s)
    assert.equal(query("SELECT count(*) FROM pg_proc WHERE pronamespace='public'::regnamespace AND proname='check_content_array_references'"), '0')
    assert.equal(query('SELECT theme_book_ids::text FROM faction_lv2'), '{missing}')
    query('DELETE FROM faction_lv2;')
    query(migration)
  })
  for (const ref of CONTENT_ARRAY_REFERENCES) {
    await t.test(`${ref.table}.${ref.column} 참조가 있는 직접 DELETE는 23503으로 원값을 보존`, () => {
      reset(createReference(ref))
      const before = snapshot()
      assert.throws(() => query("DELETE FROM contents WHERE id='drop';"), new RegExp(`23503.*${ref.table}\\.${ref.column}`, 's'))
      assert.deepEqual(snapshot(), before)
      assert.equal(orphanCount(), '0')
    })
    await t.test(`${ref.table}.${ref.column} 없는 작품을 가리키는 INSERT는 23503`, () => {
      reset('')
      query("DELETE FROM contents WHERE id='drop';")
      assert.throws(() => query(createReference(ref)), /23503.*array references a missing content/s)
      assert.equal(query(`SELECT count(*) FROM ${ref.table}`), '0')
      assert.equal(orphanCount(), '0')
    })
  }
  await t.test('실제 통합 helper가 다섯 배열을 대표 ID로 옮긴 뒤 원작품을 지운다', () => {
    reset(`
      INSERT INTO flow_nodes VALUES('node','other','["other","drop","drop"]');
      INSERT INTO flows VALUES('flow','{"S":["drop"],"D":[]}');
      INSERT INTO tier_lists VALUES('tier','{"S":["drop"]}',ARRAY['other','drop']);
      INSERT INTO faction_lv2 VALUES('faction',ARRAY['other','drop','keep']);
    `)
    const before = snapshot()
    assert.match(query(buildMergeSql({ keep: 'keep', drop: 'drop' }, { ...before, contents: before.contents.filter(row => row.id !== 'other') })), /MERGE_COMMITTED/)
    assert.equal(query("SELECT count(*) FROM contents WHERE id='drop'"), '0')
    assert.deepEqual(JSON.parse(query('SELECT bonus_content_ids FROM flow_nodes')), ['other', 'keep'])
    assert.deepEqual(JSON.parse(query('SELECT tiers FROM flows')), { D: [], S: ['keep'] })
    assert.deepEqual(JSON.parse(query('SELECT tiers FROM tier_lists')), { S: ['keep'] })
    assert.equal(query('SELECT unranked::text FROM tier_lists'), '{other,keep}')
    assert.equal(query('SELECT theme_book_ids::text FROM faction_lv2'), '{other,keep}')
    assert.equal(orphanCount(), '0')
  })
  await t.test('다섯 배열 참조가 각각 남은 ID 변경은 23503으로 원값을 보존', () => {
    for (const ref of CONTENT_ARRAY_REFERENCES) {
      reset(createReference(ref))
      const before = snapshot()
      assert.throws(() => query("UPDATE contents SET id='renamed' WHERE id='drop';"), new RegExp(`23503.*${ref.table}\\.${ref.column}`, 's'))
      assert.deepEqual(snapshot(), before)
      query("UPDATE contents SET id=id WHERE id='drop';")
      assert.deepEqual(snapshot(), before)
      assert.equal(orphanCount(), '0')
    }
  })
  await t.test('배열 참조 없는 ID 변경은 허용하고 기존 PK·일반 FK 제약은 유지', () => {
    reset('')
    query("UPDATE contents SET id='renamed' WHERE id='drop';")
    assert.equal(query("SELECT count(*) FROM contents WHERE id='renamed'"), '1')
    assert.throws(() => query("UPDATE contents SET id='renamed' WHERE id='keep';"), /23505/)
    reset("INSERT INTO member_contents(id,content_id,member_id) VALUES('member','drop','reader');")
    const before = snapshot()
    assert.throws(() => query("UPDATE contents SET id='renamed' WHERE id='drop';"), /23503/)
    assert.deepEqual(snapshot(), before)
    assert.equal(orphanCount(), '0')
  })
  await t.test('참조 없는 DELETE 및 NULL·빈 배열·중복 ID 저장은 원값 그대로 허용', () => {
    reset(`
      INSERT INTO flows VALUES('f','{"S":[],"D":null}'),('null',null);
      INSERT INTO flow_nodes VALUES('n','other',null),('duplicate','other','["keep","keep"]');
      INSERT INTO faction_lv2 VALUES('f',ARRAY[]::text[]),('null',null);
      INSERT INTO tier_lists VALUES('t','{}',ARRAY[]::text[]),('null',null,null);
    `)
    const before = snapshot()
    query("DELETE FROM contents WHERE id='drop';")
    const after = snapshot()
    assert.deepEqual(after, { ...before, contents: before.contents.filter(row => row.id !== 'drop') })
    assert.equal(orphanCount(), '0')
  })
  await t.test('배열 구조 및 문자열이 아닌 ID는 저장 전에 23514로 거절', () => {
    reset('')
    for (const sql of [
      `INSERT INTO flows VALUES('invalid','[]');`,
      `INSERT INTO flows VALUES('invalid','{"S":"keep"}');`,
      `INSERT INTO flow_nodes VALUES('invalid','other','[7]');`,
      `INSERT INTO flow_nodes VALUES('invalid','other','[null]');`,
      `INSERT INTO faction_lv2 VALUES('invalid',ARRAY[NULL]::text[]);`,
    ]) assert.throws(() => query(sql), /23514/)
    assert.equal(orphanCount(), '0')
  })
  await t.test('RLS가 배열 참조를 숨겨도 삭제 방어가 실제 참조를 확인', () => {
    reset(createReference(CONTENT_ARRAY_REFERENCES.find(ref => ref.table === 'faction_lv2')))
    query(`CREATE ROLE array_reference_test_role; GRANT USAGE ON SCHEMA public TO array_reference_test_role;
      GRANT SELECT,DELETE ON contents TO array_reference_test_role;
      GRANT SELECT ON faction_lv2 TO array_reference_test_role;
      ALTER TABLE faction_lv2 ENABLE ROW LEVEL SECURITY;
      CREATE POLICY hide_array_references ON faction_lv2 FOR SELECT USING(false);`)
    assert.equal(query('SET ROLE array_reference_test_role; SELECT count(*) FROM faction_lv2;'), '0')
    assert.throws(() => query("SET ROLE array_reference_test_role; DELETE FROM contents WHERE id='drop';"), /23503.*faction_lv2.theme_book_ids/s)
    query('ALTER TABLE faction_lv2 DISABLE ROW LEVEL SECURITY;')
    assert.equal(orphanCount(), '0')
  })
  await t.test('참조 INSERT가 먼저 시작하면 동시 DELETE는 기다린 뒤 23503으로 거절', async () => {
    reset('')
    const writer = startClient('array_insert_first', `BEGIN; INSERT INTO faction_lv2 VALUES('race',ARRAY['drop']); SELECT 'READY';`)
    await waitFor(() => writer.stdout.includes('READY'))
    const deleter = startClient('array_delete_second', "BEGIN; DELETE FROM contents WHERE id='drop'; COMMIT;")
    deleter.child.stdin.end()
    await waitFor(() => waiting('array_delete_second'))
    assert.equal((await finish(writer)).status, 0)
    const result = await deleter.done
    assert.notEqual(result.status, 0); assert.match(result.stderr, /23503/)
    assert.equal(query("SELECT count(*) FROM contents WHERE id='drop'"), '1')
    assert.equal(query('SELECT theme_book_ids::text FROM faction_lv2'), '{drop}')
    assert.equal(orphanCount(), '0')
  })
  await t.test('DELETE가 먼저 시작하면 동시 배열 UPDATE는 기다린 뒤 23503으로 거절', async () => {
    reset(`INSERT INTO flow_nodes VALUES('race','other','["keep"]');`)
    const deleter = startClient('array_delete_first', "BEGIN; DELETE FROM contents WHERE id='drop'; SELECT 'READY';")
    await waitFor(() => deleter.stdout.includes('READY'))
    const writer = startClient('array_update_second', `BEGIN; UPDATE flow_nodes SET bonus_content_ids='["drop"]' WHERE id='race'; COMMIT;`)
    writer.child.stdin.end()
    await waitFor(() => waiting('array_update_second'))
    assert.equal((await finish(deleter)).status, 0)
    const result = await writer.done
    assert.notEqual(result.status, 0); assert.match(result.stderr, /23503/)
    assert.equal(query("SELECT count(*) FROM contents WHERE id='drop'"), '0')
    assert.deepEqual(JSON.parse(query('SELECT bonus_content_ids FROM flow_nodes')), ['keep'])
    assert.equal(orphanCount(), '0')
  })
  await t.test('동시 배열 UPDATE가 먼저 시작해도 DELETE는 최신 참조를 확인', async () => {
    reset(`INSERT INTO tier_lists VALUES('race','{"S":["keep"]}',ARRAY[]::text[]);`)
    const writer = startClient('array_update_first', `BEGIN; UPDATE tier_lists SET unranked=ARRAY['drop'] WHERE id='race'; SELECT 'READY';`)
    await waitFor(() => writer.stdout.includes('READY'))
    const deleter = startClient('array_delete_after_update', "BEGIN; DELETE FROM contents WHERE id='drop'; COMMIT;")
    deleter.child.stdin.end()
    await waitFor(() => waiting('array_delete_after_update'))
    assert.equal((await finish(writer)).status, 0)
    const result = await deleter.done
    assert.notEqual(result.status, 0); assert.match(result.stderr, /23503/)
    assert.equal(query("SELECT count(*) FROM contents WHERE id='drop'"), '1')
    assert.equal(query('SELECT unranked::text FROM tier_lists'), '{drop}')
    assert.equal(orphanCount(), '0')
  })
  await t.test('배열 INSERT가 먼저 시작하면 동시 ID 변경은 기다린 뒤 최신 참조로 거절', async () => {
    reset('')
    const writer = startClient('array_before_identity_update', `BEGIN; INSERT INTO faction_lv2 VALUES('race',ARRAY['drop']); SELECT 'READY';`)
    await waitFor(() => writer.stdout.includes('READY'))
    const changer = startClient('identity_update_after_array', "BEGIN; UPDATE contents SET id='renamed' WHERE id='drop'; COMMIT;")
    changer.child.stdin.end()
    await waitFor(() => waiting('identity_update_after_array'))
    assert.equal((await finish(writer)).status, 0)
    const result = await changer.done
    assert.notEqual(result.status, 0); assert.match(result.stderr, /23503/)
    assert.equal(query("SELECT count(*) FROM contents WHERE id='drop'"), '1')
    assert.equal(query('SELECT theme_book_ids::text FROM faction_lv2'), '{drop}')
    assert.equal(orphanCount(), '0')
  })
  await t.test('ID 변경이 먼저 시작하면 옛 ID의 동시 배열 INSERT는 기다린 뒤 거절', async () => {
    reset('')
    const changer = startClient('identity_update_before_array', "BEGIN; UPDATE contents SET id='renamed' WHERE id='drop'; SELECT 'READY';")
    await waitFor(() => changer.stdout.includes('READY'))
    const writer = startClient('array_after_identity_update', `BEGIN; INSERT INTO faction_lv2 VALUES('race',ARRAY['drop']); COMMIT;`)
    writer.child.stdin.end()
    await waitFor(() => waiting('array_after_identity_update'))
    assert.equal((await finish(changer)).status, 0)
    const result = await writer.done
    assert.notEqual(result.status, 0); assert.match(result.stderr, /23503/)
    assert.equal(query("SELECT count(*) FROM contents WHERE id='renamed'"), '1')
    assert.equal(query('SELECT count(*) FROM faction_lv2'), '0')
    assert.equal(orphanCount(), '0')
  })
  for (const isolation of ['REPEATABLE READ', 'SERIALIZABLE']) {
    await t.test(`${isolation} 삭제는 snapshot 이후의 새 참조를 놓치지 않도록 40001 반환`, async () => {
      reset('')
      const deleter = startClient(`array_snapshot_${isolation.replaceAll(' ', '_')}`, `BEGIN ISOLATION LEVEL ${isolation}; SELECT count(*) FROM contents; SELECT 'READY';`)
      await waitFor(() => deleter.stdout.includes('READY'))
      query(`INSERT INTO faction_lv2 VALUES('new',ARRAY['drop']);`)
      const result = await finish(deleter, "DELETE FROM contents WHERE id='drop'; COMMIT;")
      assert.notEqual(result.status, 0); assert.match(result.stderr, /40001.*requires READ COMMITTED/s)
      assert.equal(query("SELECT count(*) FROM contents WHERE id='drop'"), '1')
      assert.equal(query('SELECT theme_book_ids::text FROM faction_lv2'), '{drop}')
      assert.equal(orphanCount(), '0')
    })
    await t.test(`${isolation} 입력은 snapshot 이후 삭제된 작품을 KEY SHARE 단계에서 거절`, async () => {
      reset('')
      const writer = startClient(`array_stale_input_${isolation.replaceAll(' ', '_')}`, `BEGIN ISOLATION LEVEL ${isolation}; SELECT count(*) FROM contents; SELECT 'READY';`)
      await waitFor(() => writer.stdout.includes('READY'))
      query("DELETE FROM contents WHERE id='drop';")
      const result = await finish(writer, `INSERT INTO faction_lv2 VALUES('new',ARRAY['drop']); COMMIT;`)
      assert.notEqual(result.status, 0); assert.match(result.stderr, /40001|23503/)
      assert.equal(query('SELECT count(*) FROM faction_lv2'), '0')
      assert.equal(orphanCount(), '0')
    })
    await t.test(`${isolation} ID가 그대로인 UPDATE는 허용하고 실제 ID 변경은 40001 반환`, () => {
      reset(createReference(CONTENT_ARRAY_REFERENCES.find(ref => ref.table === 'faction_lv2')))
      const before = snapshot()
      query(`BEGIN ISOLATION LEVEL ${isolation}; UPDATE contents SET id=id WHERE id='drop'; COMMIT;`)
      assert.deepEqual(snapshot(), before)
      assert.throws(() => query(`BEGIN ISOLATION LEVEL ${isolation}; UPDATE contents SET id='renamed' WHERE id='drop'; COMMIT;`), /40001.*requires READ COMMITTED/s)
      assert.deepEqual(snapshot(), before)
      reset('')
      assert.throws(() => query(`BEGIN ISOLATION LEVEL ${isolation}; UPDATE contents SET id='renamed' WHERE id='drop'; COMMIT;`), /40001.*requires READ COMMITTED/s)
      assert.equal(query("SELECT count(*) FROM contents WHERE id='drop'"), '1')
      assert.equal(orphanCount(), '0')
    })
  }
})
