/** 실제 PostgreSQL 회귀 검사. PG_TEST_BIN의 로컬 바이너리만 사용하고 운영 연결은 받지 않는다. */
import test from 'node:test'
import assert from 'node:assert/strict'
import { existsSync, mkdtempSync, rmSync, readFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, resolve, basename } from 'node:path'
import { spawnSync, spawn } from 'node:child_process'
import { createServer } from 'node:net'
import { editionPolicySql } from './lib/edition-policy-sql.mjs'
import { translationRepairSql } from './edition-translation-audit.mjs'
import { buildMergeSql, SNAPSHOT_TABLES } from './lib/merge-work-sql.mjs'

const bin = process.env.PG_TEST_BIN
const executable = name => join(bin, name + (process.platform === 'win32' ? '.exe' : ''))
const pair = { keep: 'keep', drop: 'drop' }
const schema = `
CREATE TABLE contents(id text PRIMARY KEY,type text,external_id text,member_count int DEFAULT 0,celeb_count int DEFAULT 0,record_count int DEFAULT 0,release_date text,metadata jsonb);
CREATE TABLE content_locales(content_id text REFERENCES contents ON DELETE CASCADE,locale text,title text,creator text,description text,isbn text,publisher text,thumbnail_url text,verified bool,sources jsonb,PRIMARY KEY(content_id,locale));
CREATE TABLE figure_book_contents(content_id text PRIMARY KEY REFERENCES contents ON DELETE RESTRICT);
CREATE TABLE figure_book_characters(content_id text REFERENCES figure_book_contents ON DELETE CASCADE,celeb_id text,relation_type text,description text,description_en text,PRIMARY KEY(content_id,celeb_id));
CREATE TABLE figure_book_editions(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,content_id text REFERENCES figure_book_contents ON DELETE CASCADE,locale text,title text,creator text,description text,isbn text,publisher text,thumbnail_url text,release_date date,edition_kind text,text_scope text,sort_order int,verified bool,sources jsonb);
CREATE UNIQUE INDEX edition_isbn ON figure_book_editions(content_id,locale,isbn) WHERE isbn IS NOT NULL;
CREATE TABLE figure_book_products(id bigint PRIMARY KEY,edition_id bigint REFERENCES figure_book_editions ON DELETE CASCADE,platform text,is_active bool);
CREATE UNIQUE INDEX active_product ON figure_book_products(edition_id,platform) WHERE is_active;
CREATE TABLE member_contents(id text PRIMARY KEY,content_id text REFERENCES contents ON DELETE CASCADE,member_id text,review text,rating int,UNIQUE(member_id,content_id));
CREATE TABLE celeb_contents(id text PRIMARY KEY,content_id text REFERENCES contents ON DELETE CASCADE,celeb_id text,review text,review_en text,source_url text,UNIQUE(celeb_id,content_id));
CREATE TABLE curated_lists(id text PRIMARY KEY);
CREATE TABLE curated_list_items(id text PRIMARY KEY,content_id text REFERENCES contents ON DELETE SET NULL,list_id text REFERENCES curated_lists,rank int,sort_order int,raw_title text,note text);
CREATE INDEX curated_item_order ON curated_list_items(list_id,sort_order);
CREATE INDEX curated_item_content ON curated_list_items(content_id);
CREATE TABLE flow_nodes(id text PRIMARY KEY,content_id text REFERENCES contents ON DELETE CASCADE,bonus_content_ids jsonb);
CREATE TABLE records(id text PRIMARY KEY,content_id text REFERENCES contents ON DELETE CASCADE,member_content_id text REFERENCES member_contents,body text);
CREATE TABLE notes(id text PRIMARY KEY,content_id text REFERENCES contents ON DELETE CASCADE,memo text);
CREATE TABLE activity_logs(id text PRIMARY KEY,content_id text REFERENCES contents(id) ON DELETE SET NULL,metadata jsonb);
CREATE TABLE commerce_events(id bigint PRIMARY KEY,content_id text REFERENCES contents ON DELETE SET NULL,kind text);
CREATE TABLE profession_book_picks(profession text,category text,content_id text REFERENCES contents ON DELETE CASCADE,sort_order int);
CREATE TABLE faction_lv2(id text PRIMARY KEY,theme_book_ids text[]);
CREATE TABLE flows(id text PRIMARY KEY,tiers jsonb);
CREATE TABLE tier_lists(id text PRIMARY KEY,tiers jsonb,unranked text[]);
CREATE FUNCTION update_counts() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
UPDATE contents c SET member_count=(SELECT count(*) FROM member_contents WHERE content_id=c.id),celeb_count=(SELECT count(*) FROM celeb_contents WHERE content_id=c.id),record_count=(SELECT count(*) FROM member_contents WHERE content_id=c.id)+(SELECT count(*) FROM celeb_contents WHERE content_id=c.id); RETURN NULL; END $$;
CREATE TRIGGER member_counts AFTER INSERT OR UPDATE OR DELETE ON member_contents FOR EACH ROW EXECUTE FUNCTION update_counts();
CREATE TRIGGER celeb_counts AFTER INSERT OR UPDATE OR DELETE ON celeb_contents FOR EACH ROW EXECUTE FUNCTION update_counts();
-- 운영 seed_figure_book_editions와 같은 카드 이관을 검증한다. 출처·검증 상태는 바꾸지 않는다.
CREATE FUNCTION seed_figure_book_editions() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
INSERT INTO figure_book_editions(content_id,locale,title,creator,description,isbn,publisher,thumbnail_url,release_date,edition_kind,text_scope,sort_order,verified,sources)
SELECT l.content_id,l.locale,coalesce(nullif(btrim(l.title),''),c.external_id,c.id),nullif(btrim(l.creator),''),l.description,nullif(btrim(l.isbn),''),nullif(btrim(l.publisher),''),l.thumbnail_url,
  CASE WHEN c.release_date ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' THEN left(c.release_date,10)::date ELSE NULL END,
  CASE WHEN c.metadata #>> '{fictionSource,editionKind}' IN ('full','abridged','retelling','adaptation','selection','volume') THEN c.metadata #>> '{fictionSource,editionKind}' ELSE NULL END,
  nullif(c.metadata #>> '{fictionSource,textScope}',''),0,l.verified,l.sources
FROM contents c JOIN content_locales l ON l.content_id=c.id WHERE c.id=NEW.content_id AND c.type='BOOK'
ON CONFLICT (content_id,locale,isbn) WHERE isbn IS NOT NULL DO NOTHING;
RETURN NEW; END $$;
CREATE TRIGGER seed_editions AFTER INSERT ON figure_book_contents FOR EACH ROW EXECUTE FUNCTION seed_figure_book_editions();
${readFileSync(new URL('../../../web/database/migrations/20261007150000_figure_book_seed_requires_physical_source.sql', import.meta.url), 'utf8')}
${readFileSync(new URL('../../../web/database/migrations/20261008120000_figure_book_seed_excludes_display_isbn.sql', import.meta.url), 'utf8')}
${readFileSync(new URL('../../../web/database/migrations/20261008170000_figure_book_seed_translation_policy.sql', import.meta.url), 'utf8')}
`

test('PostgreSQL에서 참조·이력 보존, 원자적 롤백과 동시 배열 쓰기 차단', { skip: !bin && 'PG_TEST_BIN을 로컬 PostgreSQL bin 경로로 지정하세요', timeout: 180000 }, async t => {
  assert.ok(existsSync(executable('initdb')))
  const directory = mkdtempSync(join(tmpdir(), 'feelandnote-merge-test-'))
  const data = join(directory, 'db')
  const run = (name, args, input, options = {}) => {
    const result = spawnSync(executable(name), args, { input, encoding: 'utf8', windowsHide: true, shell: false, timeout: 15000, maxBuffer: 10 * 1024 * 1024, ...options })
    if (result.error || result.status !== 0) throw new Error(result.error?.message ?? result.stderr)
    return result.stdout?.trim() ?? ''
  }
  const server = createServer()
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve))
  const port = server.address().port
  await new Promise(resolve => server.close(resolve))
  let started = false
  t.after(() => {
    if (started) run('pg_ctl', ['-D', data, '-m', 'immediate', '-w', 'stop'])
    assert.ok(resolve(directory).startsWith(resolve(tmpdir()) + (process.platform === 'win32' ? '\\' : '/')) && basename(directory).startsWith('feelandnote-merge-test-'))
    if (process.platform === 'win32') {
      const result = spawnSync('powershell', ['-NoProfile', '-Command', `Remove-Item -LiteralPath '${directory.replaceAll("'", "''")}' -Recurse`], { windowsHide: true, shell: false, encoding: 'utf8' })
      assert.equal(result.status, 0, result.stderr)
    } else rmSync(directory, { recursive: true })
  })
  run('initdb', ['-D', data, '-U', 'postgres', '-A', 'trust', '--no-locale', '--encoding=UTF8'], undefined, {timeout:120000})
  started = true
  // Windows 서버 자식이 stdio pipe를 물고 있으면 pg_ctl이 끝나도 spawnSync가 기다린다.
  run('pg_ctl', ['-D', data, '-l', join(directory, 'postgres.log'), '-o', `-h 127.0.0.1 -p ${port}`, '-w', 'start'], undefined, { stdio: 'ignore' })
  const args = ['-X', '-qAt', '-v', 'ON_ERROR_STOP=1', '-h', '127.0.0.1', '-p', String(port), '-U', 'postgres', '-d', 'postgres']
  const query = sql => run('psql', args, sql)
  query(schema)
  const reset = extra => query(`TRUNCATE ${SNAPSHOT_TABLES.join(',')} RESTART IDENTITY CASCADE; INSERT INTO contents(id,type) VALUES('keep','BOOK'),('drop','BOOK'),('other','BOOK'); ${extra}`)
  const snapshot = () => JSON.parse(query(`SELECT jsonb_build_object(${SNAPSHOT_TABLES.map(table => `'${table}',(SELECT coalesce(jsonb_agg(to_jsonb(t)),'[]'::jsonb) FROM ${table} t ${table === 'contents' ? "WHERE id IN ('keep','drop')" : ''})`).join(',')});`))
  const merge = s => query(buildMergeSql(pair, s))

  await t.test('작품 병합은 ISBN이 다른 같은 원문을 하나로 줄이고 상품 이력·감상을 보존한다', t => {
    t.after(() => query('DROP TRIGGER IF EXISTS guard_figure_book_edition_policy ON figure_book_editions'))
    reset(`UPDATE contents SET metadata='{"figureBook":{"originalLanguage":"en","identityEvidence":"https://publisher.example/book"}}' WHERE id IN ('keep','drop');
      INSERT INTO figure_book_contents VALUES('keep'),('drop');
      INSERT INTO figure_book_editions(id,content_id,locale,title,isbn,publisher,sources) VALUES
      (1,'keep','en','Original','one','Canonical Press','{"primary":"openlibrary","title":"https://openlibrary.org/books/OL1M"}'),
      (2,'drop','en','Original, revised edition','two','Other Press','{"primary":"openlibrary","title":"https://openlibrary.org/books/OL2M"}');
      INSERT INTO figure_book_products VALUES(1,1,'coupang',true),(2,2,'coupang',true);
      INSERT INTO member_contents VALUES('reader','drop','user','review',5);`)
    query(editionPolicySql())
    const before=snapshot(), representative=JSON.stringify(before.figure_book_editions.find(row=>row.id===1))
    merge(before)
    assert.equal(query('SELECT count(*) FROM figure_book_editions'), '1')
    assert.deepEqual(JSON.parse(query('SELECT to_jsonb(e)::text FROM figure_book_editions e WHERE id=1')), JSON.parse(representative))
    assert.equal(query('SELECT count(*) FROM figure_book_products WHERE edition_id=1'), '2')
    assert.equal(query('SELECT count(*) FROM figure_book_products WHERE is_active'), '1')
    assert.equal(query("SELECT content_id || ':' || review FROM member_contents WHERE id='reader'"), 'keep:review')
    query('DROP TRIGGER guard_figure_book_edition_policy ON figure_book_editions')
  })

  await t.test('작품 병합은 같은 역자의 재출간만 접고 다른 역자의 번역은 남긴다', t => {
    t.after(() => query('DROP TRIGGER IF EXISTS guard_figure_book_edition_policy ON figure_book_editions'))
    reset(`INSERT INTO figure_book_contents VALUES('keep'),('drop');
      INSERT INTO figure_book_editions(id,content_id,locale,title,isbn,sources) VALUES
      (1,'keep','ko','오디세이아','one','{"translators":["천병희"]}'),
      (2,'drop','ko','오디세이아 개정판','two','{"translators":["천 병희"]}'),
      (3,'drop','ko','오디세이아','three','{"translators":["김헌"]}');
      INSERT INTO figure_book_products VALUES(1,2,'coupang',true);`)
    query(editionPolicySql())
    merge(snapshot())
    assert.equal(query("SELECT string_agg(id::text,',' ORDER BY id) FROM figure_book_editions"), '1,3')
    assert.equal(query('SELECT edition_id FROM figure_book_products WHERE id=1'), '1')
    assert.equal(query("SELECT sources->'translators' FROM figure_book_editions WHERE id=3"), '["김헌"]')
    query('DROP TRIGGER guard_figure_book_edition_policy ON figure_book_editions')
  })

  await t.test('작품 병합은 원문·역자 근거가 없는 다른 ISBN을 임의로 접지 않는다', t => {
    t.after(() => query('DROP TRIGGER IF EXISTS guard_figure_book_edition_policy ON figure_book_editions'))
    reset(`INSERT INTO figure_book_contents VALUES('keep'),('drop');
      INSERT INTO figure_book_editions(id,content_id,locale,title,isbn,sources) VALUES
      (1,'keep','en','Same title','one','{}'),(2,'drop','en','Same title','two','{}');`)
    query(editionPolicySql())
    const before=snapshot()
    assert.throws(() => merge(before), /additional edition requires a verified different translation/u)
    assert.deepEqual(snapshot(), before)
  })

  await t.test('이동한 판본과 표시 카드의 독립 검수 근거도 새 작품을 가리킨다', () => {
    const proof = { method: 'independent_work_review', content_id: 'drop', work_identity: 'old', original_title: 'Old title', original_creator: 'Old author', isbn: 'edition-isbn', source_url: 'https://publisher.example/exact-edition' }
    const history = { ...proof, content_id: 'other', work_identity: 'historical' }
    const sources = JSON.stringify({ primary: 'kakao_book', edition_work_evidence: [proof, history], work_attribution: proof }).replaceAll("'", "''")
    reset(`UPDATE contents SET metadata='{"figureBook":{"workIdentity":"canonical","workTitle":"Canonical title","workCreator":"Canonical author"}}' WHERE id='keep';
      INSERT INTO figure_book_contents VALUES('keep'),('drop');
      INSERT INTO figure_book_editions(id,content_id,locale,title,isbn,sources) VALUES(3,'drop','ko','Edition','edition-isbn','${sources}');
      INSERT INTO content_locales(content_id,locale,title,sources) VALUES('drop','en','Display','${sources}');`)
    merge(snapshot())
    const expected = { ...proof, content_id: 'keep', work_identity: 'canonical', original_title: 'Canonical title', original_creator: 'Canonical author' }
    for (const table of ['figure_book_editions', 'content_locales']) {
      const actual = JSON.parse(query(`SELECT sources FROM ${table} WHERE content_id='keep'`))
      assert.deepEqual(actual.edition_work_evidence, [expected, history])
      assert.deepEqual(actual.work_attribution, expected)
    }
  })

  await t.test('같은 번역의 상품 참조는 대표 판본으로 옮기고 역자가 다른 판본과 감상은 남긴다', () => {
    reset(`INSERT INTO figure_book_contents VALUES('keep');
      INSERT INTO figure_book_editions(id,content_id,locale,title,isbn,sources) VALUES
      (1,'keep','ko','오디세이아','one','{"translators":["천병희"]}'),
      (2,'keep','ko','오디세이아','two','{"translators":["천병희"]}'),
      (3,'keep','ko','오디세이아','three','{"translators":["김헌"]}'),
      (4,'keep','ko','축약본','four','{}');
      INSERT INTO figure_book_products VALUES(1,1,'coupang',true),(2,2,'coupang',true);
      INSERT INTO member_contents VALUES('reader','keep','user','review',5);`)
    const before=snapshot(), keep=before.figure_book_editions.find(r=>r.id===1), drop=before.figure_book_editions.find(r=>r.id===2)
    const excluded=before.figure_book_editions.find(r=>r.id===4)
    query(translationRepairSql({duplicates:[{keep,drops:[drop]}],excluded:[{row:excluded}]},before))
    assert.equal(query("SELECT string_agg(id::text,',' ORDER BY id) FROM figure_book_editions"), '1,3')
    assert.equal(query('SELECT count(*) FROM figure_book_products WHERE edition_id=1'), '2')
    assert.equal(query('SELECT count(*) FROM figure_book_products WHERE is_active'), '1')
    assert.equal(query("SELECT review FROM member_contents WHERE id='reader'"),'review')
  })

  await t.test('축약 카드로 판본을 자동 등록하지 않는다', () => {
    reset(`INSERT INTO content_locales(content_id,locale,title,isbn,sources) VALUES('keep','ko','일론 머스크 요약본','9788934971016','{"primary":"kakao_book"}'); INSERT INTO figure_book_contents VALUES('keep');`)
    assert.equal(query('SELECT count(*) FROM figure_book_editions'), '0')
  })

  await t.test('판본 식별자 없이 제목 검색 표시만 저장된 카드는 seed와 병합에서 실판본이 되지 않는다', () => {
    reset(`INSERT INTO content_locales(content_id,locale,title,creator,sources) VALUES('drop','ko','Biography','Someone','{"primary":"kakao_book","title":"kakao_title_search","isbn":"kakao_title_search"}'); INSERT INTO figure_book_contents VALUES('drop');`)
    assert.equal(query('SELECT count(*) FROM figure_book_editions'), '0')
    assert.match(merge(snapshot()), /MERGE_COMMITTED/)
    assert.equal(query('SELECT count(*) FROM figure_book_editions'), '0')
    assert.equal(query("SELECT title FROM content_locales WHERE content_id='keep'"), 'Biography')
  })

  await t.test('표시용 제목에 복사된 ISBN은 실판본으로 생성하지 않고 병합도 검수 전 차단', () => {
    reset(`INSERT INTO content_locales(content_id,locale,title,isbn,sources) VALUES('drop','en','Translated display','9780192802552','{"primary":"none","title":"translated"}'); INSERT INTO figure_book_contents VALUES('drop');`)
    assert.equal(query('SELECT count(*) FROM figure_book_editions'), '0')
    assert.throws(() => buildMergeSql(pair, snapshot()), /display title still has an unverified ISBN/)
    assert.equal(query("SELECT isbn FROM content_locales WHERE content_id='drop'"), '9780192802552')
    assert.equal(query("SELECT count(*) FROM contents WHERE id='drop'"), '1')
  })

  await t.test('한국어 공급자 카드가 영어 원문 판본으로 자동 복제되지 않는다', () => {
    reset(`INSERT INTO content_locales(content_id,locale,title,creator,isbn,sources) VALUES
      ('drop','en','Translated title','Translated author','9788937425899','{"primary":"kakao_book"}'),
      ('drop','ko','자연의 지혜','애니 딜라드','9788937425899','{"primary":"kakao_book"}');
      INSERT INTO figure_book_contents VALUES('drop');`)
    assert.equal(query("SELECT count(*) FROM figure_book_editions WHERE locale='en'"),'0')
    assert.equal(query("SELECT count(*) FROM figure_book_editions WHERE locale='ko'"),'1')
    merge(snapshot())
    assert.equal(query("SELECT count(*) FROM figure_book_editions WHERE locale='en'"),'0')
    assert.equal(query("SELECT count(*) FROM figure_book_editions WHERE locale='ko'"),'1')
    assert.equal(query("SELECT title FROM content_locales WHERE locale='en'"),'Translated title')
  })

  await t.test('회원·감상 자식 ID, 다른 ISBN, 구매 이력과 모든 배열을 보존', () => {
    reset(`
      INSERT INTO figure_book_contents VALUES('keep'),('drop');
      INSERT INTO figure_book_editions(id,content_id,locale,isbn,title) VALUES(1,'keep','en','same','One'),(2,'drop','en','same','One'),(3,'drop','ko','different','Two');
      INSERT INTO figure_book_products VALUES(1,1,'amazon',true),(2,2,'amazon',true);
      INSERT INTO member_contents VALUES('m1','keep','u1','원문',5),('m2','drop','u2','review',4);
      INSERT INTO celeb_contents VALUES('c1','keep','c',NULL,NULL,'source'),('c2','drop','c','감상','Review','source');
      INSERT INTO figure_book_characters VALUES('keep','person','related',NULL,NULL),('drop','person','appearance','설명','Description');
      INSERT INTO records VALUES('r','drop','m2','record body'); INSERT INTO notes VALUES('n','drop','memo');
      INSERT INTO curated_lists VALUES('list') ON CONFLICT DO NOTHING;
      INSERT INTO curated_list_items(id,content_id,list_id,rank) VALUES('l','drop','list',4);
      INSERT INTO flow_nodes VALUES('node','drop','["drop","keep"]'),('bonus','other','["drop","other","other"]');
      INSERT INTO flows VALUES('f','{"다시 읽기":["drop","keep"],"D":[]}');
      INSERT INTO tier_lists VALUES('t','{"S":[]}',ARRAY['other','drop']);
      INSERT INTO faction_lv2 VALUES('f',ARRAY['other','drop','keep']);
      INSERT INTO activity_logs VALUES('a','drop','{"original":"drop"}');
    `)
    assert.match(merge(snapshot()), /MERGE_COMMITTED/)
    assert.equal(query("SELECT content_id||'|'||review||'|'||rating FROM member_contents WHERE id='m2'"), 'keep|review|4')
    assert.equal(query("SELECT member_content_id||'|'||body FROM records WHERE id='r'"), 'm2|record body')
    assert.equal(query("SELECT review||'|'||review_en FROM celeb_contents WHERE id='c1'"), '감상|Review')
    assert.equal(query("SELECT relation_type||'|'||description FROM figure_book_characters"), 'appearance|설명')
    assert.equal(query('SELECT count(*) FROM figure_book_editions'), '2')
    assert.equal(query('SELECT count(*) FROM figure_book_products'), '2')
    assert.equal(query('SELECT count(*) FROM figure_book_products WHERE is_active'), '1')
    assert.equal(query("SELECT content_id||'|'||(metadata->>'original') FROM activity_logs"), 'keep|drop')
    assert.deepEqual(JSON.parse(query("SELECT tiers FROM flows")), { D: [], '다시 읽기': ['keep'] })
    assert.deepEqual(JSON.parse(query("SELECT bonus_content_ids FROM flow_nodes WHERE id='bonus'")), ['keep', 'other', 'other'])
    assert.equal(query('SELECT member_count||\'|\'||celeb_count||\'|\'||record_count FROM contents WHERE id=\'keep\''), '2|1|3')
  })

  await t.test('같은 목록의 선정 원행 두 개는 ID·순위·메모·원제목·순서를 그대로 보존', () => {
    reset(`
      INSERT INTO curated_lists VALUES('same-list') ON CONFLICT DO NOTHING;
      INSERT INTO curated_list_items VALUES
        ('first','keep','same-list',1,126,'첫 원제목','첫 메모'),
        ('second','drop','same-list',2,127,'둘째 원제목','둘째 메모');
    `)
    const before = snapshot()
    assert.match(merge(before), /MERGE_COMMITTED/)
    const after = JSON.parse(query('SELECT jsonb_agg(to_jsonb(t) ORDER BY id) FROM curated_list_items t'))
    assert.deepEqual(after, before.curated_list_items.map(row => ({ ...row, content_id: 'keep' })).sort((a, b) => a.id.localeCompare(b.id)))
    assert.equal(query("SELECT count(*) FROM contents WHERE id='drop'"), '0')
  })

  await t.test('선정 원행의 백업 후 변경은 여전히 전체 통합을 롤백', () => {
    reset(`
      INSERT INTO curated_lists VALUES('same-list') ON CONFLICT DO NOTHING;
      INSERT INTO curated_list_items VALUES
        ('first','keep','same-list',1,126,'첫 원제목','첫 메모'),
        ('second','drop','same-list',2,127,'둘째 원제목','둘째 메모');
    `)
    const before = snapshot()
    query("UPDATE curated_list_items SET note='바뀐 메모' WHERE id='second'")
    assert.throws(() => merge(before), /concurrent change in curated_list_items/)
    assert.equal(query("SELECT content_id||'|'||note FROM curated_list_items WHERE id='second'"), 'drop|바뀐 메모')
    assert.equal(query("SELECT count(*) FROM contents WHERE id IN ('keep','drop')"), '2')
  })

  await t.test('SQL로 직접 실행해도 서로 다른 사용자 등급은 전체 롤백', () => {
    reset(`INSERT INTO flows VALUES('f','{"S":["keep"],"D":["drop"]}');`)
    assert.throws(() => merge(snapshot()), /rank conflict/)
    assert.equal(query("SELECT count(*) FROM contents WHERE id IN ('keep','drop')"), '2')
    assert.deepEqual(JSON.parse(query('SELECT tiers FROM flows')), { S: ['keep'], D: ['drop'] })
  })

  await t.test('백업 뒤 새 배열 참조가 생기면 원값 검증에서 롤백', () => {
    reset(''); const before = snapshot()
    query(`INSERT INTO flow_nodes VALUES('new','other','["drop"]');`)
    assert.throws(() => merge(before), /concurrent change in flow_nodes/)
    assert.equal(query("SELECT count(*) FROM contents WHERE id IN ('keep','drop')"), '2')
  })

  await t.test('같은 ISBN의 다른 범위와 같은 인물의 다른 설명은 원행을 남김', () => {
    reset(`INSERT INTO figure_book_contents VALUES('keep'),('drop'); INSERT INTO figure_book_editions(content_id,locale,isbn,title,text_scope) VALUES('keep','en','same','Title','volume-1'),('drop','en','same','Title','complete');`)
    assert.throws(() => merge(snapshot()), /edition scope conflict/)
    assert.equal(query('SELECT count(*) FROM figure_book_editions'), '2')
    reset(`INSERT INTO figure_book_contents VALUES('keep'),('drop'); INSERT INTO figure_book_characters VALUES('keep','c','related','first',NULL),('drop','c','related','second',NULL);`)
    assert.throws(() => merge(snapshot()), /character description conflict/)
    assert.equal(query('SELECT count(*) FROM figure_book_characters'), '2')
  })

  await t.test('운영 seed는 표시용 제목을 제외하고 공급자 판본의 실제 분권 제목을 쓴다', () => {
    reset(`
      INSERT INTO content_locales(content_id,locale,title,isbn,sources) VALUES
        ('keep','en','Translated display',NULL,'{"primary":"none","title":"translated"}'),
        ('keep','ko','Canonical work',NULL,'{"primary":"kakao_book","edition_title":"Physical volume 2"}'),
        ('drop','en','Physical ISBN','9780192802552','{"primary":"none"}'),
        ('drop','ko','Unknown display',NULL,NULL);
      INSERT INTO figure_book_contents VALUES('keep'),('drop');
    `)
    assert.equal(query('SELECT count(*) FROM figure_book_editions'), '2')
    assert.equal(query("SELECT title FROM figure_book_editions WHERE content_id='keep'"), 'Physical volume 2')
    assert.equal(query("SELECT isbn FROM figure_book_editions WHERE content_id='drop'"), '9780192802552')
    assert.equal(query("SELECT count(*) FROM figure_book_editions WHERE title IN ('Translated display','Unknown display')"), '0')
  })

  await t.test('catalog가 없던 양쪽 대표 카드는 ISBN 판본을 각각 보존', () => {
    reset(`INSERT INTO content_locales(content_id,locale,title,isbn) VALUES('keep','en','First','isbn-1'),('drop','en','Second','isbn-2');`)
    assert.match(merge(snapshot()), /MERGE_COMMITTED/)
    assert.equal(query('SELECT count(*) FROM figure_book_editions'), '2')
    assert.equal(query("SELECT string_agg(isbn,',' ORDER BY isbn) FROM figure_book_editions WHERE content_id='keep'"), 'isbn-1,isbn-2')
  })

  await t.test('catalog 없는 실판본 ISBN은 locale 충돌 후에도 남고 미확인 출처·상태를 날조하지 않음', () => {
    for (const sources of [null, { primary: 'none' }]) {
      reset(`
        INSERT INTO content_locales(content_id,locale,title,sources) VALUES('keep','en','Display','{"primary":"none","title":"translated"}');
        INSERT INTO content_locales(content_id,locale,title,creator,description,isbn,publisher,thumbnail_url,verified,sources)
          VALUES('drop','en','Hobbes','Richard Tuck','원래 소개','9780192802552','Oxford University Press','original-cover',NULL,${sources === null ? 'NULL' : `'${JSON.stringify(sources)}'`});
      `)
      const before = snapshot()
      assert.equal(before.figure_book_contents.length, 0)
      assert.equal(before.figure_book_editions.length, 0)
      assert.match(merge(before), /MERGE_COMMITTED/)
      const editions = JSON.parse(query('SELECT jsonb_agg(to_jsonb(t)) FROM figure_book_editions t'))
      assert.equal(editions.length, 1)
      const original = before.content_locales.find(row => row.content_id === 'drop')
      for (const key of ['locale', 'title', 'creator', 'description', 'isbn', 'publisher', 'thumbnail_url', 'verified', 'sources']) assert.deepEqual(editions[0][key], original[key], key)
      assert.equal(editions[0].content_id, 'keep')
      assert.equal(query("SELECT title FROM content_locales WHERE content_id='keep' AND locale='en'"), 'Display')
      assert.equal(query("SELECT count(*) FROM contents WHERE id='drop'"), '0')
    }
  })

  await t.test('keep 카드와 같은 ISBN의 drop 실판본은 원래 ID와 제품 참조를 유지', () => {
    for (const keepHasCatalog of [false, true]) {
      reset(`
        INSERT INTO figure_book_contents VALUES('drop')${keepHasCatalog ? ",('keep')" : ''};
        INSERT INTO content_locales(content_id,locale,title,isbn) VALUES('keep','en','Keeper card','9780063391420');
        INSERT INTO figure_book_editions(id,content_id,locale,title,isbn,publisher,edition_kind,text_scope,verified,sources)
          VALUES(7950,'drop','en','Original physical edition','9780063391420','Original publisher','full','complete',true,'{"primary":"openlibrary","edition_key":"original-edition"}');
        INSERT INTO figure_book_products VALUES(91,7950,'amazon',true);
      `)
      const before = snapshot()
      assert.match(merge(before), /MERGE_COMMITTED/)
      const actual = JSON.parse(query('SELECT jsonb_agg(to_jsonb(t)) FROM figure_book_editions t'))
      assert.deepEqual(actual, before.figure_book_editions.map(row => ({ ...row, content_id: 'keep' })))
      assert.deepEqual(JSON.parse(query('SELECT jsonb_agg(to_jsonb(t)) FROM figure_book_products t')), before.figure_book_products)
      assert.equal(query("SELECT isbn FROM content_locales WHERE content_id='keep' AND locale='en'"), '9780063391420')
    }
  })

  await t.test('ISBN 없는 실제 공급자 판본도 locale 충돌 뒤 남고 표시용 제목은 판본으로 만들지 않음', () => {
    reset(`INSERT INTO content_locales(content_id,locale,title,sources) VALUES('keep','en','Display','{"primary":"none","title":"translated"}'),('drop','en','Provider edition','{"primary":"openlibrary","title":"https://openlibrary.org/books/OL1M"}');`)
    assert.match(merge(snapshot()), /MERGE_COMMITTED/)
    assert.equal(query("SELECT count(*) FROM figure_book_editions"), '1')
    assert.equal(query("SELECT title FROM figure_book_editions WHERE content_id='keep'"), 'Provider edition')
  })

  await t.test('ISBN 없는 표시 카드도 ISBN을 확인한 실판본을 중복 생성하지 않는다', () => {
    for (const isbn of [null, '9780728003484']) {
      reset(`INSERT INTO figure_book_contents VALUES('keep'),('drop');
        INSERT INTO content_locales(content_id,locale,title,creator,sources) VALUES('keep','ko','The Syngman Rhee Telegrams','중앙일보 외','{"primary":"kakao_book","isbn":"kakao_title_search","edition_title":"THE SYNGMAN RHEE TELEGRAMS 1","series_title":"The Syngman Rhee Telegrams"}');
        INSERT INTO figure_book_editions(id,content_id,locale,title,creator,isbn,publisher,sources) VALUES(27258,'keep','ko','THE SYNGMAN RHEE TELEGRAMS 1','중앙일보 외',${isbn ? "'" + isbn + "'" : 'NULL'},'국학자료원','{"primary":"kakao_book","isbn":"kakao_title_search","edition_work_evidence":[{"source_url":"https://lib.mois.go.kr/"}]}');
        INSERT INTO figure_book_products VALUES(91,27258,'coupang',true);`)
      const before = snapshot()
      assert.match(merge(before), /MERGE_COMMITTED/)
      assert.deepEqual(JSON.parse(query('SELECT jsonb_agg(to_jsonb(t)) FROM figure_book_editions t')), before.figure_book_editions)
      assert.deepEqual(JSON.parse(query('SELECT jsonb_agg(to_jsonb(t)) FROM figure_book_products t')), before.figure_book_products)
    }
  })

  await t.test('회원 중복과 새로운 cascade FK는 삭제 전 차단', () => {
    reset(`INSERT INTO member_contents VALUES('m1','keep','u','one',1),('m2','drop','u','two',2);`)
    assert.throws(() => merge(snapshot()), /member duplicate/)
    assert.equal(query('SELECT count(*) FROM member_contents'), '2')
    reset(`CREATE TABLE unhandled(id int,content_id text REFERENCES contents ON DELETE CASCADE); INSERT INTO unhandled VALUES(1,'drop');`)
    assert.throws(() => merge(snapshot()), /unhandled contents FK/)
    assert.equal(query('SELECT count(*) FROM unhandled'), '1')
    query('DROP TABLE unhandled')
  })

  await t.test('운영 DB 가드는 축약 직접 쓰기·동일 역자 중복을 막고 다른 번역과 상품을 허용한다', () => {
    reset(`INSERT INTO figure_book_contents VALUES('keep');`)
    query(editionPolicySql())
    assert.throws(() => query("INSERT INTO figure_book_editions(content_id,locale,title,edition_kind) VALUES('keep','ko','책','abridged')"), /Abridged books/)
    assert.throws(() => query("INSERT INTO figure_book_editions(content_id,locale,title) VALUES('keep','en','Penguin Readers Level 3: Elon Musk')"), /graded readers/)
    for(const title of ['문학평전 1 [영어원서] (문학평전 1)','교훈집 / Plutarch Morals 영문판','하이아워서의 노래 | 영문판 |']) assert.throws(() => query(`INSERT INTO figure_book_editions(content_id,locale,title) VALUES('keep','ko','${title}')`), /Abridged books/)
    assert.throws(() => query("INSERT INTO figure_book_editions(content_id,locale,title,text_scope) VALUES('keep','ko','후속 권','volume/41')"), /Abridged books/)
    assert.throws(() => query("INSERT INTO figure_book_editions(content_id,locale,title,text_scope) VALUES('keep','en','The Story of the Stone','volume IV of V')"), /Abridged books/)
    assert.throws(() => query(`INSERT INTO figure_book_editions(content_id,locale,title,sources) VALUES('keep','en','Doctor Zhivago','{"provider_scope_description":"Penguin Reader , Level 5 (2300 words)"}')`), /graded readers/)
    assert.throws(() => query(`INSERT INTO figure_book_editions(content_id,locale,title,isbn,sources) VALUES('keep','en','Elon Musk','9788934971016','{"provider_edition_isbn":"9788934971016","provider_edition_title":"Penguin Readers Level 3: Elon Musk"}');`), /graded readers/)
    assert.throws(() => query(`INSERT INTO figure_book_editions(content_id,locale,title,isbn,sources) VALUES('keep','ko','설득','original','{\"provider_edition_isbn\":\"original\",\"provider_edition_title\":\"설득 (영문원서-제인 오스틴)\"}');`), /Abridged books/)
    query(`INSERT INTO figure_book_editions(id,content_id,locale,title,sources) VALUES(200,'keep','ko','오디세이아','{"translators":["천병희"]}');`)
    assert.throws(() => query(`INSERT INTO figure_book_editions(content_id,locale,title,sources) VALUES('keep','ko','오뒷세이아 특별판','{"translators":["천 병희"]}');`), /representative edition/)
    query(`INSERT INTO figure_book_editions(id,content_id,locale,title,sources) VALUES(201,'keep','ko','오디세이아','{"translators":["김헌"]}'); INSERT INTO figure_book_products VALUES(201,200,'coupang',true);`)
    assert.equal(query('SELECT count(*) FROM figure_book_editions'),'2')
    assert.throws(() => query("INSERT INTO figure_book_editions(content_id,locale,title,isbn) VALUES('keep','ko','미확인 상품','new-product')"), /verified different translation/)
    query(`UPDATE contents SET metadata='{"figureBook":{"originalLanguage":"en","identityEvidence":"https://www.wikidata.org/wiki/Q1"}}' WHERE id='keep';
      INSERT INTO figure_book_editions(content_id,locale,title,isbn) VALUES('keep','en','Original','original');
      INSERT INTO figure_book_editions(content_id,locale,title,isbn,sources) VALUES('keep','en','Different translation','translated','{"translators":["B. O. Foster"]}');`)
    assert.throws(() => query("INSERT INTO figure_book_editions(content_id,locale,title,isbn) VALUES('keep','en','Original paperback','paperback')"), /representative edition/)
    assert.throws(() => query(`INSERT INTO figure_book_editions(content_id,locale,title,isbn,sources) VALUES('keep','en','Same translation hardcover','hardcover','{"translators":["B O Foster"]}');`), /representative edition/)
    assert.equal(query("SELECT public.book_translator_identity('[\".\"]') IS NULL"),'t')
    query(`UPDATE contents SET metadata='{"figureBook":{"workTitle":"Journey to the West","series":{"sourceUrl":"https://publisher.example/series"}}}' WHERE id='keep';`)
    assert.throws(() => query("INSERT INTO figure_book_editions(content_id,locale,title) VALUES('keep','en','The Journey to the West, Revised Edition, Volume 3')"), /Abridged books/)
    assert.equal(query("SELECT public.book_nonstart_work_volume('Journey to the West, Volume 0','{\"workTitle\":\"Journey to the West\"}','chapters-051-075')"),'f')
    assert.equal(query("SELECT public.book_nonstart_work_volume('Journey to the West, Volume IV','{\"workTitle\":\"Journey to the West\"}','chapters-051-075')"),'t')
    query('DROP TRIGGER guard_figure_book_edition_policy ON figure_book_editions')
  })

  await t.test('행이 없던 배열에도 다른 세션은 합병 중 ID를 삽입할 수 없음', async () => {
    reset('')
    const sql = buildMergeSql(pair, snapshot()).replace('COMMIT;', 'SELECT pg_sleep(0.6);\nCOMMIT;')
    const child = spawn(executable('psql'), args, { windowsHide: true, shell: false, stdio: ['pipe', 'pipe', 'pipe'] })
    let output = '', error = ''; child.stdout.on('data', x => { output += x }); child.stderr.on('data', x => { error += x })
    const completion = new Promise(resolve => child.on('exit', code => resolve(code)))
    child.stdin.end(sql)
    // 행 잠금은 빈 표를 보호하지 않는다. relation lock이 실제 취득됐는지 확인한다.
    for (let attempt = 0; attempt < 25; attempt++) {
      if (query("SELECT count(*) FROM pg_locks WHERE relation='flows'::regclass AND mode='ShareRowExclusiveLock' AND granted") === '1') break
      await new Promise(resolve => setTimeout(resolve, 20))
    }
    assert.throws(() => query(`SET lock_timeout='100ms'; INSERT INTO flows VALUES('late','{"S":["drop"]}');`), /lock timeout/)
    assert.equal(await completion, 0, error)
    assert.match(output, /MERGE_COMMITTED/)
  })
})
