'use client'

import { useState, useEffect, useCallback, useMemo } from 'react'
import {
  buildTitle, buildDescription, calcChapterTimestamps,
  type EpisodeMeta, type YouTubeMeta, type YouTubeLink, type EpisodeForChapters, type BookForDesc,
} from '@feelandnote/shared/lib/youtube-meta'

const BTN = 'px-3 py-1 rounded text-sm font-semibold'
const BTN_PRIMARY = `bg-accent text-bg-main ${BTN} hover:bg-accent-hover`
const BTN_SECONDARY = `bg-bg-card border border-border ${BTN} hover:bg-bg-hover`
const TAG = 'text-[10px] px-1.5 py-0.5 rounded font-mono'

type VariantInfo = {
  lang: 'ko' | 'en'
  type: 'longform' | 'shorts'
  video: { exists: boolean; size: number; name: string } | null
  srt: { exists: boolean; name: string } | null
  thumb: { exists: boolean; name: string } | null
}

type ChannelAuth = { authenticated: boolean; expiryDate?: string }

type YouTubeStatus = {
  auth: { ko: ChannelAuth; en: ChannelAuth }
  lineup: EpisodeMeta | null
  variants: VariantInfo[]
  meta: YouTubeMeta | null
}

type EpisodeData = EpisodeForChapters & {
  host: { nickname: string; nickname_en?: string }
  books: BookForDesc[]
}

type VariantKey = 'ko-longform' | 'ko-shorts' | 'en-longform' | 'en-shorts'
type MetaEntry = { title: string; description: string; links: YouTubeLink[] }

type Props = {
  series: string
  name: string
  post: (url: string, body: unknown) => Promise<void>
}

function formatSize(bytes: number): string {
  if (bytes >= 1024 * 1024 * 1024) return `${(bytes / (1024 * 1024 * 1024)).toFixed(1)}GB`
  if (bytes >= 1024 * 1024) return `${(bytes / (1024 * 1024)).toFixed(0)}MB`
  return `${(bytes / 1024).toFixed(0)}KB`
}

const VARIANT_KEYS: VariantKey[] = ['ko-longform', 'ko-shorts', 'en-longform', 'en-shorts']

export function YouTubePanel({ series, name, post }: Props) {
  const [status, setStatus] = useState<YouTubeStatus | null>(null)
  const [loading, setLoading] = useState(true)
  const [epKo, setEpKo] = useState<EpisodeData | null>(null)
  const [epEn, setEpEn] = useState<EpisodeData | null>(null)
  const [dryRun, setDryRun] = useState(false)
  const [uploadMsg, setUploadMsg] = useState<string | null>(null)
  const [uploadLog, setUploadLog] = useState<string[] | null>(null)
  const [openVariant, setOpenVariant] = useState<VariantKey | null>(null)
  const [editMeta, setEditMeta] = useState<Record<VariantKey, MetaEntry>>({} as any)
  const [editingLineup, setEditingLineup] = useState(false)
  const [lineupDraft, setLineupDraft] = useState<EpisodeMeta | null>(null)
  const [saving, setSaving] = useState(false)

  // EN 페이지에서도 base name으로 YouTube API 호출
  const baseName = name.endsWith('-en') ? name.slice(0, -3) : name

  // --- 데이터 로드 ---

  const fetchStatus = useCallback(() => {
    setLoading(true)
    fetch(`/api/${series}/youtube/status?episode=${baseName}`)
      .then(r => r.json())
      .then(setStatus)
      .catch(() => {})
      .finally(() => setLoading(false))
  }, [series, baseName])

  useEffect(() => { fetchStatus() }, [fetchStatus])

  useEffect(() => {
    fetch(`/api/${series}/episodes/${baseName}`)
      .then(r => r.ok ? r.json() : null)
      .then(setEpKo)
      .catch(() => {})
    fetch(`/api/${series}/episodes/${baseName}-en`)
      .then(r => r.ok ? r.json() : null)
      .then(setEpEn)
      .catch(() => {})
  }, [series, baseName])

  // --- 자동 생성 값 ---

  const autoGenerated = useMemo(() => {
    const result: Partial<Record<VariantKey, MetaEntry>> = {}
    const lineupMeta = status?.lineup

    for (const key of VARIANT_KEYS) {
      const [lang, type] = key.split('-') as ['ko' | 'en', 'longform' | 'shorts']
      const ep = lang === 'ko' ? epKo : epEn
      if (!ep) continue

      const celebName = lang === 'ko' ? ep.host.nickname : (ep.host.nickname_en ?? ep.host.nickname)
      const isShorts = type === 'shorts'
      const title = lineupMeta
        ? buildTitle(lineupMeta, celebName, lang, isShorts)
        : `${lang === 'ko' ? '[서재탐방]' : '[Library Tour]'} ${celebName}`

      let chapters: { time: string; label: string }[] | undefined
      if (!isShorts) {
        try { chapters = calcChapterTimestamps(ep, lang) } catch { /* fallback */ }
      }

      const description = buildDescription(celebName, ep.books, lang, isShorts, chapters, undefined, baseName)
      result[key] = { title, description, links: [] }
    }
    return result
  }, [status?.lineup, epKo, epEn])

  // editMeta 초기화: meta 있으면 override, 없으면 autoGenerated
  useEffect(() => {
    const merged: Record<string, MetaEntry> = {}
    for (const key of VARIANT_KEYS) {
      const auto = autoGenerated[key]
      const saved = status?.meta?.[key]
      merged[key] = {
        title: saved?.title ?? auto?.title ?? '',
        description: saved?.description ?? auto?.description ?? '',
        links: saved?.links ?? [],
      }
    }
    setEditMeta(merged as Record<VariantKey, MetaEntry>)
  }, [autoGenerated, status?.meta])

  // --- 이벤트 핸들러 ---

  const saveMeta = async () => {
    await fetch(`/api/${series}/youtube/meta?episode=${baseName}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(editMeta),
    })
  }

  const handleUpload = async (lang?: string, type?: string) => {
    const label = [lang?.toUpperCase(), type].filter(Boolean).join(' ') || '전체'
    setUploadMsg(`${label} 메타 저장 중...`)
    setUploadLog(null)

    // 업로드 전 메타 자동 저장
    await saveMeta()

    setUploadMsg(`${label} ${dryRun ? '드라이런' : '업로드'} 요청 중...`)

    const res = await fetch(`/api/${series}/youtube/upload`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ episode: baseName, lang, type, dry: dryRun }),
    })
    if (!res.ok) {
      const err = await res.json().catch(() => ({ error: res.statusText }))
      setUploadMsg(`실패: ${err.error ?? res.statusText}`)
      return
    }

    const { taskId } = await res.json()
    setUploadMsg(`${label} ${dryRun ? '드라이런' : '업로드'} 진행 중...`)

    // 태스크 직접 폴링
    const poll = setInterval(async () => {
      try {
        const tr = await fetch(`/api/tasks/${taskId}`)
        if (!tr.ok) return
        const task = await tr.json()
        setUploadLog(task.log?.slice(-20) ?? [])
        if (task.status !== 'running') {
          clearInterval(poll)
          setUploadMsg(task.status === 'done'
            ? `${label} ${dryRun ? '드라이런' : '업로드'} 완료`
            : `${label} 오류 발생`)
        }
      } catch { /* ignore */ }
    }, 1500)
  }

  const handleSaveMeta = async () => {
    setSaving(true)
    try {
      await saveMeta()
      fetchStatus()
    } finally { setSaving(false) }
  }

  const handleResetVariant = (key: VariantKey) => {
    const auto = autoGenerated[key]
    if (!auto) return
    setEditMeta(prev => ({ ...prev, [key]: { ...auto } }))
  }

  const handleSaveLineup = async () => {
    if (!lineupDraft) return
    setSaving(true)
    try {
      await fetch(`/api/${series}/youtube/lineup?episode=${baseName}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(lineupDraft),
      })
      setEditingLineup(false)
      fetchStatus()
    } finally { setSaving(false) }
  }

  const updateMeta = (key: VariantKey, field: 'title' | 'description', value: string) => {
    setEditMeta(prev => ({ ...prev, [key]: { ...prev[key], [field]: value } }))
  }

  // --- 렌더링 ---

  if (loading) return <div className="text-text-dim text-sm">로딩...</div>
  if (!status) return <div className="text-error-text text-sm">상태 조회 실패</div>

  const { auth, lineup, variants } = status
  const disabled = !auth.ko.authenticated && !auth.en.authenticated

  return (
    <div className="space-y-4">
      {/* 인증 + 편성 정보 */}
      <LineupHeader
        auth={auth}
        lineup={lineup}
        editing={editingLineup}
        draft={lineupDraft}
        onEdit={() => { setEditingLineup(true); setLineupDraft(lineup ?? { hook: { ko: '', en: '' } }) }}
        onCancel={() => setEditingLineup(false)}
        onSave={handleSaveLineup}
        onDraftChange={setLineupDraft}
        onRefresh={fetchStatus}
        saving={saving}
      />

      {(!auth.ko.authenticated || !auth.en.authenticated) && (
        <div className="text-xs text-error-text space-y-0.5">
          {!auth.ko.authenticated && <p>KO 채널 미인증 — pnpm youtube:auth</p>}
          {!auth.en.authenticated && <p>EN 채널 미인증 — pnpm youtube:auth -- --channel en</p>}
        </div>
      )}

      {/* Variant 아코디언 */}
      <div className="space-y-1">
        {variants.map((v) => {
          const key = `${v.lang}-${v.type}` as VariantKey
          const isOpen = openVariant === key
          const meta = editMeta[key]
          const hasOverride = status.meta?.[key] != null

          return (
            <VariantRow
              key={key}
              variant={v}
              series={series}
              name={name}
              isOpen={isOpen}
              meta={meta}
              hasOverride={hasOverride}
              disabled={disabled}
              onToggle={() => setOpenVariant(isOpen ? null : key)}
              onUpdateMeta={(field, value) => updateMeta(key, field, value)}
              onUpdateLinks={(links) => setEditMeta(prev => ({ ...prev, [key]: { ...prev[key], links } }))}
              onReset={() => handleResetVariant(key)}
              onUpload={() => handleUpload(v.lang, v.type)}
            />
          )
        })}
      </div>

      {/* 하단 액션 바 */}
      <div className="flex items-center gap-2 pt-2 border-t border-border">
        <button onClick={handleSaveMeta} disabled={saving} className={`${BTN_SECONDARY} ${saving ? 'opacity-50' : ''}`}>
          메타 저장
        </button>
        <button onClick={() => handleUpload()} disabled={disabled} className={`${BTN_PRIMARY} ${disabled ? 'opacity-30 cursor-default' : ''}`}>
          전체 업로드
        </button>
        <button onClick={() => handleUpload('ko')} disabled={disabled} className={`${BTN_SECONDARY} ${disabled ? 'opacity-30 cursor-default' : ''}`}>
          KO만
        </button>
        <button onClick={() => handleUpload('en')} disabled={disabled} className={`${BTN_SECONDARY} ${disabled ? 'opacity-30 cursor-default' : ''}`}>
          EN만
        </button>
        <label className="ml-auto flex items-center gap-1.5 text-xs text-text-secondary cursor-pointer select-none">
          <input type="checkbox" checked={dryRun} onChange={e => setDryRun(e.target.checked)} className="accent-accent" />
          드라이런
        </label>
      </div>
      {uploadMsg && (
        <p className="text-xs text-accent animate-pulse">{uploadMsg}</p>
      )}
      {uploadLog && uploadLog.length > 0 && (
        <pre className="bg-bg-main border border-border rounded p-2 text-[11px] font-mono text-text-secondary max-h-48 overflow-y-auto whitespace-pre-wrap">
          {uploadLog.join('\n')}
        </pre>
      )}
    </div>
  )
}

// ─── LineupHeader ────────────────────────────────────────

function LineupHeader({ auth, lineup, editing, draft, onEdit, onCancel, onSave, onDraftChange, onRefresh, saving }: {
  auth: { ko: ChannelAuth; en: ChannelAuth }
  lineup: EpisodeMeta | null
  editing: boolean
  draft: EpisodeMeta | null
  onEdit: () => void
  onCancel: () => void
  onSave: () => void
  onDraftChange: (d: EpisodeMeta) => void
  onRefresh: () => void
  saving: boolean
}) {
  if (editing && draft) {
    return (
      <div className="space-y-2 p-2 rounded bg-bg-main border border-accent/40">
        <div className="flex items-center gap-2 text-sm">
          <label className="text-text-dim w-14 shrink-0">훅(KO)</label>
          <input
            value={draft.hook.ko}
            onChange={e => onDraftChange({ ...draft, hook: { ...draft.hook, ko: e.target.value } })}
            className="flex-1 bg-bg-card border border-border rounded px-2 py-0.5 text-sm text-text-primary"
          />
        </div>
        <div className="flex items-center gap-2 text-sm">
          <label className="text-text-dim w-14 shrink-0">훅(EN)</label>
          <input
            value={draft.hook.en}
            onChange={e => onDraftChange({ ...draft, hook: { ...draft.hook, en: e.target.value } })}
            className="flex-1 bg-bg-card border border-border rounded px-2 py-0.5 text-sm text-text-primary"
          />
        </div>
        <div className="flex gap-2">
          <button onClick={onSave} disabled={saving} className={`${BTN_PRIMARY} text-xs ${saving ? 'opacity-50' : ''}`}>저장</button>
          <button onClick={onCancel} className={`${BTN_SECONDARY} text-xs`}>취소</button>
        </div>
      </div>
    )
  }

  return (
    <div className="space-y-1">
      <div className="flex items-center gap-3 text-sm">
        <span className="flex items-center gap-1.5">
          <span className={`w-2 h-2 rounded-full ${auth.ko.authenticated ? 'bg-green-500' : 'bg-red-500'}`} />
          KO
        </span>
        <span className="flex items-center gap-1.5">
          <span className={`w-2 h-2 rounded-full ${auth.en.authenticated ? 'bg-green-500' : 'bg-red-500'}`} />
          EN
        </span>
        {lineup ? (
          <>
            <button onClick={onEdit} className="text-text-dim hover:text-accent text-xs">[수정]</button>
          </>
        ) : (
          <>
            <span className="text-warning-text text-xs">편성표 미등록</span>
            <button onClick={onEdit} className="text-accent text-xs hover:underline">[등록]</button>
          </>
        )}
        <button onClick={onRefresh} className="ml-auto text-text-dim hover:text-text-primary text-xs">새로고침</button>
      </div>
      {lineup && (
        <div className="text-xs text-text-dim space-y-0.5">
          <div>훅(KO): {lineup.hook.ko}</div>
          <div>훅(EN): {lineup.hook.en}</div>
        </div>
      )}
    </div>
  )
}

// ─── VariantRow ──────────────────────────────────────────

function VariantRow({ variant: v, series, name, isOpen, meta, hasOverride, disabled, onToggle, onUpdateMeta, onUpdateLinks, onReset, onUpload }: {
  variant: VariantInfo
  series: string
  name: string
  isOpen: boolean
  meta: MetaEntry | undefined
  hasOverride: boolean
  disabled: boolean
  onToggle: () => void
  onUpdateMeta: (field: 'title' | 'description', value: string) => void
  onUpdateLinks: (links: YouTubeLink[]) => void
  onReset: () => void
  onUpload: () => void
}) {
  const langLabel = v.lang.toUpperCase()
  const typeLabel = v.type === 'longform' ? '롱폼' : '쇼츠'
  const baseName = name.endsWith('-en') ? name.slice(0, -3) : name
  const label = baseName.split('-').map(w => w[0].toUpperCase() + w.slice(1)).join('')

  return (
    <div className="rounded bg-bg-main border border-border overflow-hidden">
      {/* 접힌 헤더 */}
      <div className="flex items-center gap-3 p-2 hover:bg-bg-hover">
        <div role="button" tabIndex={0} onClick={onToggle} onKeyDown={e => e.key === 'Enter' && onToggle()}
          className="flex items-center gap-3 flex-1 min-w-0 cursor-pointer">
          <span className="text-text-dim text-xs w-4">{isOpen ? '▾' : '▸'}</span>
          {/* 썸네일 */}
          <div className="w-12 h-8 rounded bg-bg-card overflow-hidden shrink-0 flex items-center justify-center">
            {v.thumb ? (
              <img src={`/api/${series}/youtube/thumb/${label}/${v.lang.toUpperCase()}/${v.thumb.name}`} alt="" className="w-full h-full object-cover" />
            ) : (
              <span className="text-text-dim text-[8px]">—</span>
            )}
          </div>
          <span className={`${TAG} ${v.lang === 'ko' ? 'bg-blue-900/40 text-blue-400' : 'bg-purple-900/40 text-purple-400'}`}>
            {langLabel}
          </span>
          <span className="font-semibold text-text-primary text-sm">{typeLabel}</span>
          {v.video ? (
            <span className="text-text-dim text-xs">{formatSize(v.video.size)}</span>
          ) : (
            <span className="text-warning-text text-xs">렌더 필요</span>
          )}
          {v.srt && <span className={`${TAG} bg-bg-card text-text-secondary`}>SRT</span>}
          {v.thumb && <span className={`${TAG} bg-bg-card text-text-secondary`}>THUMB</span>}
          {hasOverride && <span className={`${TAG} bg-accent/20 text-accent`}>커스텀</span>}
        </div>
        <button
          onClick={onUpload}
          disabled={disabled || !v.video}
          className={`${BTN_SECONDARY} text-xs shrink-0 ${disabled || !v.video ? 'opacity-30 cursor-default' : ''}`}
        >업로드</button>
      </div>

      {/* 펼친 편집 영역 */}
      {isOpen && meta && (
        <div className="px-3 pb-3 space-y-2 border-t border-border">
          <div className="pt-2">
            <label className="text-[10px] text-text-dim uppercase tracking-wider">제목</label>
            <input
              value={meta.title}
              onChange={e => onUpdateMeta('title', e.target.value)}
              className="w-full bg-bg-card border border-border rounded px-2 py-1 text-sm text-text-primary font-mono mt-0.5"
            />
          </div>
          <div>
            <label className="text-[10px] text-text-dim uppercase tracking-wider">설명</label>
            <textarea
              value={meta.description}
              onChange={e => onUpdateMeta('description', e.target.value)}
              rows={v.type === 'longform' ? 16 : 6}
              className="w-full bg-bg-card border border-border rounded px-2 py-1 text-xs text-text-primary font-mono mt-0.5 leading-relaxed resize-y"
            />
          </div>
          {/* 링크 편집 */}
          <div>
            <label className="text-[10px] text-text-dim uppercase tracking-wider">링크</label>
            <div className="space-y-1 mt-1">
              {(meta.links ?? []).map((link, i) => (
                <div key={i} className="flex items-center gap-1.5">
                  <input
                    value={link.label}
                    onChange={e => {
                      const next = [...meta.links]; next[i] = { ...next[i], label: e.target.value }; onUpdateLinks(next)
                    }}
                    placeholder="라벨"
                    className="w-32 bg-bg-card border border-border rounded px-2 py-0.5 text-xs text-text-primary"
                  />
                  <input
                    value={link.url}
                    onChange={e => {
                      const next = [...meta.links]; next[i] = { ...next[i], url: e.target.value }; onUpdateLinks(next)
                    }}
                    placeholder="https://..."
                    className="flex-1 bg-bg-card border border-border rounded px-2 py-0.5 text-xs text-text-primary font-mono"
                  />
                  <button onClick={() => { const next = meta.links.filter((_, j) => j !== i); onUpdateLinks(next) }}
                    className="text-red-400 text-xs hover:text-red-300 shrink-0 px-1">✕</button>
                </div>
              ))}
              <button
                onClick={() => onUpdateLinks([...(meta.links ?? []), { label: '', url: '' }])}
                className="text-accent text-xs hover:underline">
                + 링크 추가
              </button>
            </div>
          </div>
          <div className="flex justify-end">
            <button onClick={onReset} className={`${BTN_SECONDARY} text-xs`}>기본값 복원</button>
          </div>
        </div>
      )}
    </div>
  )
}
